### ISSUE TITLE
Enhancement - IOT function compatibility with the Wireguard server (Asuswrt-Merlin 388.1)

### ISSUE THREAD

**Issue by grifos** [Adamm00/IPSet_ASUS#103]
Hello Adam, I hope you are doing well.

You may already be planning this, if not it would be great if you could add Wireguard server compatibility to the IOT function, like it already has with OpenVPN, so that remote clients connecting to the router through the Wireguard server can get access to devices on the IOT list.

As of now this isn't working and there is no workaround possible as far as I can tell as the IOT rules are inserted above all others on the FORWARD table.

Thank you.

All the best,
Grifos

**Comment by Adamm00** [comment]
Personally, I don't use wireguarrd so it's hard for me to test. If you could make a pull request or point me in the right direction on what needs to be changed I can take a look.

**Comment by grifos** [comment]
Hi Adam, first of all thank you so much for having already updated Skynet and also for looking into this request.

I don't know how exactly this could be done but below is the code that has to be expanded to support wireguard for IOT devices, `tun2+` covers the OpenVPN servers 1 and 2 interfaces, the equivalent for the wireguard servers would be `wgs+` so the outcome should be that `tun2+ or wgs+` are permitted.

`admin@r1:/jffs/scripts# cat firewall | grep tun2+
	iptables -D FORWARD -i br+ -m set --match-set Skynet-IOT src ! -o tun2+ -j LOG --log-prefix "[BLOCKED - IOT] " --log-tcp-sequence --log-tcp-options --log-ip-options 2>/dev/null
			iptables -I FORWARD "$pos5" -i br+ -m set --match-set Skynet-IOT src ! -o tun2+ -j LOG --log-prefix "[BLOCKED - IOT] " --log-tcp-sequence --log-tcp-options --log-ip-options 2>/dev/null
		iptables -D FORWARD -i br+ -m set --match-set Skynet-IOT src ! -o tun2+ -j DROP 2>/dev/null
		iptables -I FORWARD -i br+ -m set --match-set Skynet-IOT src ! -o tun2+ -j DROP 2>/dev/null
		iptables -C FORWARD -i br+ -m set --match-set Skynet-IOT src ! -o tun2+ -j DROP 2>/dev/null || fail="${fail}#9 "
			iptables -C FORWARD -i br+ -m set --match-set Skynet-IOT src ! -o tun2+ -j LOG --log-prefix "[BLOCKED - IOT] " --log-tcp-sequence --log-tcp-options --log-ip-options 2>/dev/null || fail="$"
admin@r1:/jffs/scripts# 
`

**Comment by grifos** [comment]
Unfortunately the code formatting hasn't come out very well, I'll try again, anyways if you do a `cat firewall | grep tun2+` on your router you'll see it well.

`
admin@r1:/jffs/scripts# cat firewall | grep tun2+
iptables -D FORWARD -i br+ -m set --match-set Skynet-IOT src ! -o tun2+ -j LOG --log-prefix "[BLOCKED - IOT] " --log-tcp-sequence --log-tcp-options --log-ip-options 2>/dev/null
iptables -I FORWARD "$pos5" -i br+ -m set --match-set Skynet-IOT src ! -o tun2+ -j LOG --log-prefix "[BLOCKED - IOT] " --log-tcp-sequence --log-tcp-options --log-ip-options 2>/dev/null
iptables -D FORWARD -i br+ -m set --match-set Skynet-IOT src ! -o tun2+ -j DROP 2>/dev/null
iptables -I FORWARD -i br+ -m set --match-set Skynet-IOT src ! -o tun2+ -j DROP 2>/dev/null
iptables -C FORWARD -i br+ -m set --match-set Skynet-IOT src ! -o tun2+ -j DROP 2>/dev/null || fail="${fail}#9 "
iptables -C FORWARD -i br+ -m set --match-set Skynet-IOT src ! -o tun2+ -j LOG --log-prefix "[BLOCKED - IOT] " --log-tcp-sequence --log-tcp-options --log-ip-options 2>/dev/null || fail="$"
admin@r1:/jffs/scripts# 
`

**Comment by grifos** [comment]
I'm closing this as I no longer own an Asus router since I've migrated to OpenWRT, so I wouldn't be able to test this enhancement if it's implemented.

Many thanks for your work on Skynet over the years Adam, it was a good ride while it lasted.

All the best,
grifos

**Comment by kevdliu** [comment]
FYI I made a PR for this here https://github.com/Adamm00/IPSet_ASUS/pull/135
