### ISSUE TITLE
Enhancement: Add function in Asus-Merlin UI to be able to update BAN list (Skynet or scMerlin webpage)

### ISSUE THREAD

**Issue by steveg2088** [Adamm00/IPSet_ASUS#108]
This is in consideration of a future enhancement.  

Normally, not sure whom else does, I have ssh access disabled and only activate as needed.  Meanwhile, sometimes I wish to update the ban list (re. amtm ... skynet menu option 3 then 1).  

So the consideration is to add a function ("update Skynet BANLIST") in the Asus-merlin UI either on the Skynet page itself (where stats are) OR perhaps part of the scMerlin scripts/webpage.  

Please consider.  No issue if you think it is not a good idea.

**Comment by Adamm00** [comment]
Feel free to submit a pull request. My skills are limited in the web dev side of things so skynet webui relies on community pull requests
