### ISSUE TITLE
Enhancement/Feature request: Change log level (to Info)

### ISSUE THREAD

**Issue by rmariboe** [Adamm00/IPSet_ASUS#109]
###### Brief Description Of Issue
Blocked connections are logged as "Warning"

###### Expected Behaviour
Would prefer "Info" level (or even the ability to choose via UI) to avoid flooding log management with "Warnings" :)

**Comment by rmariboe** [comment]
Could of course change levels manually by replacing iptables rules but...

**Comment by mrbardman** [comment]
Agree!

**Comment by Adamm00** [comment]
Stats can be disabled via the settings menu, when stats are enabled you get logging. Unfortunately there is no way around this.
