### ISSUE TITLE
Lock File Detected (banmalware)

### ISSUE THREAD

**Issue by yecarrillo** [Adamm00/IPSet_ASUS#11]
###### Brief Description Of Issue;
------------
After successive re-installations, skynet didn´t restart

<br><br>
###### Steps To Reproduce Issue;
------------
/usr/sbin/curl --retry 3 "https://raw.githubusercontent.com/Adamm00/IPSet_ASUS/master/firewall.sh" -o "/jffs/scripts/firewall" && chmod +x /jffs/scripts/firewall && /jffs/scripts/firewall install

<br><br>
###### Expected Behaviour;
------------
firewall process running

<br><br>
###### Output of ( sh /jffs/scripts/firewall debug info );
------------
Skynet Version; v6.3.1 (17/07/2018)
iptables v1.4.14 - (ppp0 @ 192.168.200.1)
ipset v6.32, protocol version: 6
FW Version; 380.70_0 (Apr 9 2018) (2.6.36.4brcmarm)
Install Dir; /tmp/mnt/DATA/skynet (9.5G / 12.2G Space Available)
SWAP File; /tmp/mnt/DATA/myswap.swp (513.0M)
Boot Args; /jffs/scripts/firewall start skynetloc=/tmp/mnt/DATA/skynet
Lock File Detected (banmalware) (pid=13001)
Locked Processes Generally Take 1-2 Minutes To Complete And May Result In Temporarily "Failed" Tests

0 IPs / 0 Ranges Banned. 0 New IPs / 0 New Ranges Banned. 0 Inbound / 0 Outbound Connections Blocked!

<br><br>

**Comment by Adamm00** [comment]
The output suggests Skynet is booting up as expected;

> Lock File Detected (banmalware) (pid=13001)
Locked Processes Generally Take 1-2 Minutes To Complete And May Result In Temporarily "Failed" Tests

If you need further help I suggest using the SNBForums thread

**Comment by 0sy** [comment]
I had experienced something similar. Re-installing did not fix the issue.

I went into debug menu (12) and re-created the SWAP file. For me, that fixed it.
