### ISSUE TITLE
SkyNEt Fails on Merlin 388.2 Beta 2 

### ISSUE THREAD

**Issue by ElmerFudd79** [Adamm00/IPSet_ASUS#115]

**Comment by jumpsmm7** [comment]
> Skynet will not stay runnin on Merlin 388.2 Beta 2 Firmware with my AX88U pro. I install and it runs but I cannot update the log under the GUI-> Firewall->Skynet. Once, I reboot the router, Firewall fails to start... AMTM-> Skynet says Fail. If I uninstall and install again, I can get back to where I started but it fails again as soon as I reboot. ![F9C72242-F5F5-4641-8C34-E28CDA965A15](https://user-images.githubusercontent.com/130384013/230932960-6ed0cd4b-e58f-4199-9f38-06a3ce86b29d.jpeg)

It is working on my RT-AX88PRO!
![image](https://user-images.githubusercontent.com/49514613/234673354-b1929eb4-5783-4355-95b8-55ed00ff7b36.png)
