### ISSUE TITLE
Currently /32 are ending up in Ranges, when instead they should be in single IP.

### ISSUE THREAD

**Issue by jumpsmm7** [Adamm00/IPSet_ASUS#119]
###### Brief Description Of Issue
Current coding places /32 subnets (single IP addresses with subnet indicator) inside the Ranges ipset which greatly reduces the amount of elements that can be placed in here with greater subnets. 

I have submitted a pull request that improves the detection and resolves the issue with better Regexp logic through skynet pull request channel. 

https://github.com/Adamm00/IPSet_ASUS/pull/122

@Adamm00 I wanted to take the time to illustrate that some of the improvements I added in the pull request above improved the overall list processing times of skynet

![image](https://user-images.githubusercontent.com/49514613/236678307-057de143-6423-4cf4-b2de-bdd4de715c56.png)

**Comment by Adamm00** [comment]
https://github.com/Adamm00/IPSet_ASUS/commit/f7c0e7a5c4d359132d49f8af028919d69c990fa4
