### ISSUE TITLE
Issue with long TLD's?

### ISSUE THREAD

**Issue by crkinard** [Adamm00/IPSet_ASUS#125]
I try and add this domain to Skynet and 'nothing happens'.

firewall ban domain dns.google

[i] Adding dns.google To Blacklist
[i] Saving Changes

No IP's are added to the ban list.

Short (two letter) TLD's seem to work fine.

**Comment by dave14305** [comment]
Same underlying issue as #111

**Comment by jumpsmm7** [comment]
> I try and add this domain to Skynet and 'nothing happens'.
> 
> firewall ban domain dns.google
> 
> [i] Adding dns.google To Blacklist [i] Saving Changes
> 
> No IP's are added to the ban list.
> 
> Short (two letter) TLD's seem to work fine.

8.8.8.8 is a hard-coded unbannable address.
