### ISSUE TITLE
False positives & Whitelist for GrapheneOS

### ISSUE THREAD

**Issue by Iconology** [Adamm00/IPSet_ASUS#128]
###### Brief Description Of Issue
A good chunk of false positives within Skynet-BlockedRanges

###### Steps To Reproduce Issue
These are all blocked within Skynet-BlockedRanges, so here are the IPs you need to whitelist if you are using Graphene OS.

```
51.79.54.68 - Graphene Network Connectivity Check - (Wi-Fi Check)
209.141.37.35 - Graphene Network Connectivity Check - (Wi-Fi Check)
51.79.74.15 - Graphene Apps Updates.
167.114.114.114 - Graphene Apps Updates.
51.222.159.48 - Graphene Releases.
51.222.140.199 - Graphene Releases.
192.99.43.50 - Graphene Releases.
```
```
Whitelist not related to GrapheneOS but useful,
192.241.245.161 - Openweather API
192.241.187.136 - Openweather API
192.241.167.16 - Openweather API

```
###### Expected Behaviour
These shouldn't be blocked. They are necessary for the OS to function properly.

Appears to be related to the same issue [#90 ](https://github.com/Adamm00/IPSet_ASUS/issues/90). Is there a more elegant solution or an update in the works? Or must I simply monitor the debug log for false positives and manually whitelist?

Regardless, thanks for making this, Adam. Even if it can't reasonably be corrected. Hopefully this whitelist helps someone out.

**Comment by Adamm00** [comment]
I don't control blacklist content unfortunately, I just give users the ability to use them. Your best bet is to always monitor your logs if your experiencing any issues and dial it in.
