### ISSUE TITLE
Q: manually update malware lists

### ISSUE THREAD

**Issue by thob** [Adamm00/IPSet_ASUS#13]
can this be done?

**Comment by Atavic** [comment]
[Here Are Some Example Update Commands](https://www.snbforums.com/threads/skynet-asus-firewall-addition-dynamic-malware-country-manual-ip-blocking.16798/), just scroll down till you read: USAGE

**Comment by thob** [comment]
`sh /jffs/scripts/firewall update` it is?

**Comment by Adamm00** [comment]
> Here Are Some Example Banmalware Commands;
( sh /jffs/scripts/firewall banmalware ) This Bans IPs From The Predefined Filter List
( sh /jffs/scripts/firewall banmalware google.com/filter.list ) This Uses The Fitler List From The Specified URL
( sh /jffs/scripts/firewall banmalware reset ) This Will Reset Skynet Back To The Default Filter URL
( sh /jffs/scripts/firewall banmalware exclude "list1.ipset|list2.ipset" ) This Will Exclude Lists Matching The Names "list1.ipset list2.ipset" From The Current Filter (Quotes And Pipes Are Nessessary For Seperating Multiple Entries!)
( sh /jffs/scripts/firewall banmalware exclude reset ) This Will Reset The Exclusion List
