### ISSUE TITLE
Gui Info

### ISSUE THREAD

**Issue by nunomgsantos80** [Adamm00/IPSet_ASUS#133]
Hello,

After the last update, in gui mode, the information and graphics no longer appear.

**Skynet Statistics
 Monitoring From - N/A
 Log Size - N/A**

Skynet Version; v7.4.6 (18/09/2023) (054315d592e0b6e1fbd846cfcff7f4b0).

**Comment by nunomgsantos80** [comment]
admin@RT-AC68U-77D0:/tmp/home/root# nvram get message_loglevel
5
admin@RT-AC68U-77D0:/tmp/home/root# nvram get log_level
7

**Comment by jumpsmm7** [comment]
> admin@RT-AC68U-77D0:/tmp/home/root# nvram get message_loglevel 5 admin@RT-AC68U-77D0:/tmp/home/root# nvram get log_level 7

Try refreshing the page after manually updating the gui

**Comment by nunomgsantos80** [comment]
Hi,
I've refreshed and rebooted but the problem persists.

**Comment by jumpsmm7** [comment]
> Hi, I've refreshed and rebooted but the problem persists.

Have you tried running a forced update? It is possible it might not have downloaded everything correctly. On occassion people have issues with downloading all components from github and have to redownload.

**Comment by nunomgsantos80** [comment]
Hi jumpsmm7,

After a force update it seems to be OK now.
I'll wait a bit longer to see if the information is updated.
Thanks for the tip.

**Comment by nunomgsantos80** [comment]
Resolved, many thks.
