### ISSUE TITLE
VPN Server Support

### ISSUE THREAD

**Issue by belleDESiRE** [Adamm00/IPSet_ASUS#134]
I am running an openvpn server on my asus router, with diversion and skynet.

Devices connected by vpn to my router are not logging any blocked outbound connections for skynet.
If these same devices connect to the network directly they are.

Issue is also described here:
https://www.snbforums.com/threads/when-connecting-to-my-openvpn-server-on-router-no-outbound-blocks-being-logged-anymore.86909/

It seems that skynet does not support openvpn server configurations currently?

**Comment by Adamm00** [comment]
Thanks for pointing this out, don't know how I ever missed it.

**Comment by belleDESiRE** [comment]
Cool, tested, works!
Tx!

**Comment by Adamm00** [comment]
Wireguard server is also now supported.

https://github.com/Adamm00/IPSet_ASUS/commit/1ceb9c7f953ae490a3fd9eee575f99d0e340e956
