### ISSUE TITLE
Getting 'IPSets failed' when iot proto switched to all or tcp

### ISSUE THREAD

**Issue by belleDESiRE** [Adamm00/IPSet_ASUS#140]
looks like an issue on line 542

![Screenshot 2024-02-06 193014](https://github.com/Adamm00/IPSet_ASUS/assets/24789925/08905bae-4fe6-4874-894c-12874b7f5de0)

**Comment by Adamm00** [comment]
I can't reproduce this, please post the full error and debug info output

**Comment by belleDESiRE** [comment]
changed the file locally, fixed the issue.

lines 542-544 in the screenshot should be still part of the else block before (insert between line 540 and 541)

**Comment by Adamm00** [comment]
Sorry I see the issue now. Nice find. Thanks
