### ISSUE TITLE
Enhancement: Show iot ports and allowed protocols at view blocked devices

### ISSUE THREAD

**Issue by belleDESiRE** [Adamm00/IPSet_ASUS#141]
It would be handy to be able to see the port list and protocols allowed for iot devices.
A logical place would be to add it to the (end of the) list of blocked devices (11 --> 11 --> 3)

Maybe also show the current configured iot port list when configuring a new list at 'Add Custom Allowed Ports'

**Comment by Adamm00** [comment]
Thanks for the suggestion
