### ISSUE TITLE
Module check fails on 3006.102.1

### ISSUE THREAD

**Issue by dave14305** [Adamm00/IPSet_ASUS#152]
https://github.com/Adamm00/IPSet_ASUS/blob/909d406da0b623d325d20307a3ebed6716e0ab7e/firewall.sh#L5446-L5449
Module is built into the kernel in 3006 code.

https://www.snbforums.com/threads/skynet-on-gt-be-98-pro.90571/

**Comment by Adamm00** [comment]
Thanks, was going to wait for updated Gnuton builds but that may be longer than expected so will push this now.

https://github.com/Adamm00/IPSet_ASUS/commit/087f30c1a0c23bafa3ac601079646e5326a169e3
