### ISSUE TITLE
can't add domain to whitelist with dash in domain.

### ISSUE THREAD

**Issue by bengalih** [Adamm00/IPSet_ASUS#158]
###### Brief Description Of Issue
Unable to add a site to the domain whitelist because (presumable) it has a dash in the name.

###### Steps To Reproduce Issue
4 >2 > URL = u-speed.net

###### Expected Behaviour
Domain is added to whitelist

###### Output of ( sh /jffs/scripts/firewall debug info )
Router Model; RT-AC68U
Skynet Version; v7.6.3 (27/07/2024) (319a580d2ec003b4e6647fdbf889dc77)
iptables v1.4.15 - (eth0 @ 10.10.10.1)
ipset v7.6, protocol version: 7
IP Address; (XXXXXXXXX) - (XXXXXXXXXXXXX::/64)
FW Version; 386.3_2 (Aug 6 2021) (2.6.36.4brcmarm)
Install Dir; /tmp/mnt/flash_drive/skynet (4.0G / 7.9G Space Available)
SWAP File; /tmp/mnt/flash_drive/myswap.swp (2.0G)
Banned Countries; cn
Uptime; 20 days, 4 hours, 59 minutes.
Ram Available; (139M / 249M)

--------------------                | ----------
| Test Description |                | | Result |
--------------------                | ----------

Internet-Connectivity               | [Passed]
Public IP Address                   | [Passed]
Write Permission                    | [Passed]
Config File                         | [Passed]
Firewall-Start Entry                | [Passed]
Services-Stop Entry                 | [Passed]
Service-Event Entry                 | [Passed]
Profile.add Entry                   | [Passed]
SWAP File                           | [Passed]
Cron Jobs                           | [Passed]
NTP Sync                            | [Passed]
Log Level 7 Settings                | [Passed]
Duplicate Rules In RAW              | [Passed]
IPSets                              | [Passed]
IPTables Rules                      | [Passed]
Local WebUI Files                   | [Passed]
Mounted WebUI Files                 | [Passed]
MenuTree.js Entry                   | [Passed]

-----------                         | ----------
| Setting |                         | | Status |
----------                          | ----------

Skynet Auto-Updates                 | [Enabled]
Malware List Auto-Updates           | [Enabled]
Logging                             | [Enabled]
Filter Traffic                      | [Selective]
Unban PrivateIP                     | [Enabled]
Log Invalid Packets                 | [Disabled]
Import AiProtect Data               | [Enabled]
Secure Mode                         | [Enabled]
Fast Switch List                    | [Disabled]
Syslog Location                     | [Default]
IOT Blocking                        | [Disabled]
IOT Logging                         | [Enabled]
Country Lookup For Stats            | [Enabled]
CDN Whitelisting                    | [Enabled]
Display WebUI                       | [Enabled]

18/18 Tests Sucessful

**Comment by dave14305** [comment]
What if you run the CLI equivalent?
```
firewall whitelist domain u-speed.net
```

**Comment by dave14305** [comment]
This u-speed.net domain has no IP when Skynet runs `nslookup u-speed.net`. Maybe whitelist the relevant sub-domain, if any.

**Comment by bengalih** [comment]
No this does not work either.  No errors, it just doesn't parse it properly and so nothing get done.

**Comment by dave14305** [comment]
> No this does not work either. No errors, it just doesn't parse it properly and so nothing get done.

There’s nothing to parse because nslookup returns an error for that domain.

**Comment by bengalih** [comment]
No, it doesn't get added there either.

However, you are correct, there is no SOA for that domain.

It's strange, the actual site I needed access to is file.u-speed.net, but file.u-speed.net is not a subdomain, it is a host (A record in u-speed.net).  So, I assumed, like I normally do for properly hosted DNS that adding the domain would be a "wildcard" to allow all A records in that domain.  I believe that has worked for me in the past, but perhaps not (I don't whitelist too many things).

In this case, I would say the issue is that the people maintaining the DNS records for that domain are either not doing it with best practices, or maybe there is an mis-understanding on my part how the whitelist domain feature is meant to work.

If I add the specific host A record for file.u-speed.net then I can get it to work, but something about this doesn't sit right with me since I am not whitelisting a "domain" when I add that, I'm acutally whitelisting a specific host (A) record.
