### ISSUE TITLE
Support for John's Merlin fork

### ISSUE THREAD

**Issue by gurabli** [Adamm00/IPSet_ASUS#19]
Hi,
I'm running John's fork on my RT-N66U, and the latest version of Skynet doesn't support this fw version (newer needed). Is there an older version or a fork that I could use?
Thanks

Edit: sorry, I just found: https://github.com/Adamm00/IPSet_ASUS/wiki#ipset-extensions-not-enabled

**Comment by Adamm00** [comment]
Unfortunately only ARM/HND routers are supported (AC56U and newer). MIPS routers run too old of a kernel to support the required IPSet modules.
