### ISSUE TITLE
Whitelist double CIDS

### ISSUE THREAD

**Issue by wbartels** [Adamm00/IPSet_ASUS#20]
###### Brief Description Of Issue
In the Whitelist_CDN () function ASN CIDS are added two times.

###### Steps To Reproduce Issue
For example this will output all CIDS from AS714 double:
`curl -fsL --retry 3 "https://ipinfo.io/AS714" | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}'`

Below is a short section form the https://ipinfo.io/AS714 source output.
You can see that the same CIDS is in the href and inside the a tag.
```
        <td>
            
            <a href="/AS714/144.178.0.0/19" >
                144.178.0.0/19
            </a>
            
        </td>
```

###### Possible workaround
Add _grep -oE '<a href="\/AS.+>'_ to the line like:  
`curl -fsL --retry 3 "https://ipinfo.io/$asn" | grep -oE '<a href="\/AS.+>' | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}' | awk -v asn="$asn" '{printf "add Skynet-Whitelist %s comment \"CDN-Whitelist: %s \"\n", $1, asn }' &`

One grep with a look-behind solution would be nicer, but on a Asuswrt routers with a Merlin firmware the grep -P (perl-style regexes) is not supported.

**Comment by Adamm00** [comment]
While technically you are correct, we actually negate this in two ways further on in the function as an (albeit minor) optimization. 

`			{
			# Apple AS714 | Akamai AS12222 AS16625 | HighWinds AS33438 AS20446 | Fastly AS54113
			for asn in AS714 AS12222 AS16625 AS33438 AS20446 AS54113; do
				curl -fsL --retry 3 "https://ipinfo.io/$asn" | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}' | awk -v asn="$asn" '{printf "add Skynet-Whitelist %s comment \"CDN-Whitelist: %s \"\n", $1, asn }' &
			done
			wait
			curl -fsL --retry 3 https://www.cloudflare.com/ips-v4 | grep -E '([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}' | awk '{printf "add Skynet-Whitelist %s comment \"CDN-Whitelist: CloudFlare \"\n", $1 }'
			curl -fsL --retry 3 https://ip-ranges.amazonaws.com/ip-ranges.json | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}' | awk '{printf "add Skynet-Whitelist %s comment \"CDN-Whitelist: Amazon \"\n", $1 }';
			} | awk '!x[$0]++' | ipset restore -!`


The first being the awk command "awk '!x[$0]++'" which removes duplicates from all of the output inside the curley braces {}. The second being the ipset restore command using the ignore flag (!), by using this flag rather then ipset stopping when it tries to add a duplicate entry, it instead silently continues.

Thanks anyway for the bug report

**Comment by wbartels** [comment]
Hello Adamm00,

Thanks for the explanation!
And sorry for the incorrect bug report.
Still I have learned something new.

Willem
