### ISSUE TITLE
dos2unix changes datestamp in "${skynetloc}"/lists/

### ISSUE THREAD

**Issue by wbartels** [Adamm00/IPSet_ASUS#24]
###### Fix
Change line nr: 3155 

from: 
dos2unix "${skynetloc}"/lists/* 2>/dev/null

to:
dos2unix --keepdate "${skynetloc}"/lists/* 2>/dev/null

or:
dos2unix -k "${skynetloc}"/lists/* 2>/dev/null

**Comment by Adamm00** [comment]
Good suggestion, unfortunately the stripped down busybox binary doesn't support any additional flags.

`skynet@RT-AX88U-DC28:/tmp/home/root# dos2unix --keepdate
dos2unix: unrecognized option '--keepdate'
BusyBox v1.25.1 (2019-12-16 00:06:35 EST) multi-call binary.

Usage: dos2unix [-ud] [FILE]

Convert FILE in-place from DOS to Unix format.
When no file is given, use stdin/stdout.

	-u	dos2unix
	-d	unix2dos
`
