### ISSUE TITLE
eval needed?

### ISSUE THREAD

**Issue by wbartels** [Adamm00/IPSet_ASUS#26]
###### Brief Description Of Issue
Is this really needed?
```
command="curl -fsLZ $(awk -F / '{print $0 " -Oz " $5 " "}' /jffs/shared-Skynet-whitelist | xargs)"
eval "$command"
```
I'm a little concert because I read on many forums using eval is dangerous, and should be avoided whenever possible. 

Wthout eval seems to work to:
`curl -fsLZ $(awk -F / '{print $0 " -Oz " $5 " "}' /jffs/shared-Skynet-whitelist | xargs)`

Or did you use it for debugging the new code?

**Comment by Adamm00** [comment]
Used for POSIX compliance. Due to word splitting the properly formatted string (note the quotes);

curl -fsLZ "$(awk -F / '{print $0 " -Oz " $5 " "}' /jffs/shared-Skynet-whitelist | xargs)"

Doesn't work because curl treats the command substitution as one word. 

```
skynet@RT-AX88U-DC28:/tmp/home/root# sh -x test.sh
+ + xargs
awk -F / {print $0 " -Oz " $5 " "} /jffs/shared-Skynet-whitelist
+ curl -fLZ https://iplists.firehol.org/files/alienvault_reputation.ipset -Oz alienvault_reputation.ipset https://iplists.firehol.org/files/bds_atif.ipset -Oz bds_atif.ipset https://iplists.firehol.org/files/bi_sshd_2_30d.ipset -Oz bi_sshd_2_30d.ipset https://iplists.firehol.org/files/blocklist_net_ua.ipset -Oz blocklist_net_ua.ipset https://iplists.firehol.org/files/coinbl_ips.ipset -Oz coinbl_ips.ipset https://iplists.firehol.org/files/cybercrime.ipset -Oz cybercrime.ipset https://iplists.firehol.org/files/dyndns_ponmocup.ipset -Ozdyndns_ponmocup.ipset https://iplists.firehol.org/files/et_block.netset -Oz et_block.netset https://iplists.firehol.org/files/et_compromised.ipset -Oz et_compromised.ipset https://iplists.firehol.org/files/firehol_level2.netset -Oz firehol_level2.netset https://iplists.firehol.org/files/firehol_level3.netset -Oz firehol_level3.netset https://iplists.firehol.org/files/normshield_high_attack.ipset -Oz normshield_high_attack.ipset https://iplists.firehol.org/files/normshield_high_bruteforce.ipset -Oz normshield_high_bruteforce.ipset https://iplists.firehol.org/files/ransomware_online.ipset -Oz ransomware_online.ipset https://iplists.firehol.org/files/ransomware_rw.ipset -Oz ransomware_rw.ipset https://iplists.firehol.org/files/spamhaus_edrop.netset -Oz spamhaus_edrop.netset https://iplists.firehol.org/files/urandomusto_ssh.ipset -Oz urandomusto_ssh.ipset https://iplists.firehol.org/files/urandomusto_telnet.ipset -Oz urandomusto_telnet.ipset https://iplists.firehol.org/files/urlvir.ipset -Oz urlvir.ipset https://iplists.firehol.org/files/uscert_hidden_cobra.ipset -Ozuscert_hidden_cobra.ipset
curl: (22) The requested URL returned error: 404 Not Found
```


But if we remove the quotes (and thus POSIX compliance, it executes correctly.

```
skynet@RT-AX88U-DC28:/tmp/mnt/USB/skynet/lists# sh -x /tmp/home/root/test.sh
+ + xargs
awk -F / {print $0 " -Oz " $5 " "} /jffs/shared-Skynet-whitelist
+ curl -fLZ https://iplists.firehol.org/files/alienvault_reputation.ipset -Oz alienvault_reputation.ipset https://iplists.firehol.org/files/bds_atif.ipset -Oz bds_atif.ipset https://iplists.firehol.org/files/bi_sshd_2_30d.ipset -Oz bi_sshd_2_30d.ipset https://iplists.firehol.org/files/blocklist_net_ua.ipset -Oz blocklist_net_ua.ipset https://iplists.firehol.org/files/coinbl_ips.ipset -Oz coinbl_ips.ipset https://iplists.firehol.org/files/cybercrime.ipset -Oz cybercrime.ipset https://iplists.firehol.org/files/dyndns_ponmocup.ipset -Ozdyndns_ponmocup.ipset https://iplists.firehol.org/files/et_block.netset -Oz et_block.netset https://iplists.firehol.org/files/et_compromised.ipset -Oz et_compromised.ipset https://iplists.firehol.org/files/firehol_level2.netset -Oz firehol_level2.netset https://iplists.firehol.org/files/firehol_level3.netset -Oz firehol_level3.netset https://iplists.firehol.org/files/normshield_high_attack.ipset -Oz normshield_high_attack.ipset https://iplists.firehol.org/files/normshield_high_bruteforce.ipset -Oz normshield_high_bruteforce.ipset https://iplists.firehol.org/files/ransomware_online.ipset -Oz ransomware_online.ipset https://iplists.firehol.org/files/ransomware_rw.ipset -Oz ransomware_rw.ipset https://iplists.firehol.org/files/spamhaus_edrop.netset -Oz spamhaus_edrop.netset https://iplists.firehol.org/files/urandomusto_ssh.ipset -Oz urandomusto_ssh.ipset https://iplists.firehol.org/files/urandomusto_telnet.ipset -Oz urandomusto_telnet.ipset https://iplists.firehol.org/files/urlvir.ipset -Oz urlvir.ipset https://iplists.firehol.org/files/uscert_hidden_cobra.ipset -Ozuscert_hidden_cobra.ipset
DL% UL%  Dled  Uled  Xfers  Live   Qd Total     Current  Left    Speed
  0 --  1040k     0    20     0     0  0:00:01  0:00:02 --:--:--  497k
```

So while it is ideally something I want to avoid, there's not many other obvious solutions I can think of.

**Comment by wbartels** [comment]
What do you think from this workaround?
```
argument="$(awk -F / '{print $0 " -Oz " $5 " "}' /jffs/shared-Skynet-whitelist | xargs)"
curl -fsLZ $argument
```

**Comment by wbartels** [comment]
PS, in my situation the `sh -x test.sh` command give results outside the terminal windows.
Can it be piped to e text file?

**Comment by Adamm00** [comment]
> argument="$(awk -F / '{print $0 " -Oz " $5 " "}' /jffs/shared-Skynet-whitelist | xargs)"
> curl -fsLZ $argument

We run into the same issue here, in POSIX all command substitutions $() and vars are supposed to be double quoted. The problem is quoting disables word splitting so curl thinks of the output as just one long word. This is one of the only use cases where word splitting is ideal but unfortunately that goes against POSIX compliance. 

I'll keep this issue open for the time being to remind myself to look for a better solution in future but our options are quite limited. 

FWIW eval isn't always terrible, the main issue is when the input isn't correctly sanitized and leaves the door open for command injection etc, but on a system like this where everything already runs as root its less of an issue.

**Comment by Adamm00** [comment]
> PS, in my situation the `sh -x test.sh` command give results outside the terminal windows.
> Can it be piped to a text file?

Output of any command can be piped by adding a trailing ">" followed by an output file name, for example

`sh -x test.sh > output.txt`

**Comment by wbartels** [comment]
Thanks for the feedback and patience!

**Comment by wbartels** [comment]
> Output of any command can be piped by adding a trailing ">" followed by an output file name, for example
> 
> `sh -x test.sh > output.txt`
Gives an empty output.txt

`ls > output.txt`
Does work

**Comment by Dabombber** [comment]
Isn't this the whole point of having the xargs command?

```sh
awk -F/ '{print $0" -Oz "$NF}' /jffs/addons/shared-whitelists/shared-Skynet-whitelist | xargs "$curlpath" -fsLZ
```

Another option would be to use the argument list as an array, but that might mess with the rest of the script if you're still using them somewhere later

```sh
set --
while read -r LINE; do 
	set -- "$@" "$LINE" '-Oz' "${LINE##*/}"
done </jffs/addons/shared-whitelists/shared-Skynet-whitelist
"$curlpath" -fsLZ "$@"
```

**Comment by Adamm00** [comment]
> Isn't this the whole point of having the xargs command?
> 
> ```shell
> awk -F/ '{print $0" -Oz "$NF}' /jffs/addons/shared-whitelists/shared-Skynet-whitelist | xargs "$curlpath" -fsLZ
> ```
> 
> Another option would be to use the argument list as an array, but that might mess with the rest of the script if you're still using them somewhere later
> 
> ```shell
> set --
> while read -r LINE; do 
> 	set -- "$@" "$LINE" '-Oz' "${LINE##*/}"
> done </jffs/addons/shared-whitelists/shared-Skynet-whitelist
> "$curlpath" -fsLZ "$@"
> ```

Ah, I completely forgot about xargs, thanks nice find. Will be added in the next version.
