### ISSUE TITLE
cat shared-Skynet-whitelist, is this correct?

### ISSUE THREAD

**Issue by fdx90** [Adamm00/IPSet_ASUS#3]
Is this correct, shouldn't that be the white-listed entries?

**Skynet: [INFO] Skynet Up To Date - v5.1.1**
**admin@AC88U:/jffs# cat shared-Skynet-whitelist**
_https://www.abuseat.org/iotcc.txt
https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_level2.netset
https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_level3.netset
https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/feodo.ipset
https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bambenek_c2.ipset
https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/spamhaus_drop.netset
https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/spamhaus_edrop.netset
https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/malwaredomainlist.ipset
https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/hphosts_exp.ipset
https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/hphosts_hjk.ipset
https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/hphosts_mmt.ipset
https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/maxmind_proxy_fraud.ipset
https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/cybercrime.ipset
https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bbcan177_ms1.netset
https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bbcan177_ms3.netset
https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/dyndns_ponmocup.ipset
https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/ransomware_feed.ipset
https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/ransomware_rw.ipset
https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/ransomware_cryptowall_ps.ipset
https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/ransomware_locky_ps.ipset
https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/et_block.netset
https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/et_compromised.ipset
https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/et_botcc.ipset
https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/blocklist_de_bots.ipset
https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/blocklist_de_ssh.ipset
https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/blocklist_de_strongips.ipset
https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/alienvault_reputation.ipset
https://raw.githubusercontent.com/shounak-de/misc-scripts/master/telemetry_and_scanners.txt_

**Comment by Adamm00** [comment]
Current implementation is correct. That file is for other scripts (example AB-Solution) to whitelist external hosts we pull files from (in this case banmalware lists).

As this file is for URL's only, I can't add all whitelisted entries, but I may look into adding entries from "whitelist domain xxx.com" as we log the domain entered with the IP entry.

**Comment by Adamm00** [comment]
As of v5.1.2 Skynet will add manually whitelisted domains (plus a few hardcoded ones) to /jffs/shared-Skynet2-whitelist so other scripts can also utilize them.
