### ISSUE TITLE
filter.list outdated?

### ISSUE THREAD

**Issue by wbartels** [Adamm00/IPSet_ASUS#35]
###### Brief Description Of Issue
Many ipsets on the filter.list are not updated anymore or even discontinued.

###### filter.list with comment
https://iplists.firehol.org/files/alienvault_reputation.ipset
https://iplists.firehol.org/files/bds_atif.ipset
https://iplists.firehol.org/files/bi_sshd_2_30d.ipset
https://iplists.firehol.org/files/blocklist_net_ua.ipset
https://iplists.firehol.org/files/coinbl_ips.ipset # Fri Sep 28 2018
https://iplists.firehol.org/files/cybercrime.ipset
https://iplists.firehol.org/files/dyndns_ponmocup.ipset
https://iplists.firehol.org/files/et_block.netset
https://iplists.firehol.org/files/et_compromised.ipset
https://iplists.firehol.org/files/firehol_level2.netset
https://iplists.firehol.org/files/firehol_level3.netset
https://iplists.firehol.org/files/normshield_high_attack.ipset # Thu Oct 17 2019
https://iplists.firehol.org/files/normshield_high_bruteforce.ipset # Thu Oct 17 2019
https://iplists.firehol.org/files/ransomware_online.ipset # Discontinued on Dec 8th, 2019
https://iplists.firehol.org/files/ransomware_rw.ipset # Discontinued on Dec 8th, 2019
https://iplists.firehol.org/files/spamhaus_edrop.netset
https://iplists.firehol.org/files/urandomusto_ssh.ipset # Wed Aug 29 2018
https://iplists.firehol.org/files/urandomusto_telnet.ipset # Wed Aug 29 2018
https://iplists.firehol.org/files/urlvir.ipset # Wed Dec 11 2019
https://iplists.firehol.org/files/uscert_hidden_cobra.ipset # Thu Jun 07 2018

###### Suggestion
Clean up the list and looking for some alternative sets.

**Comment by Adamm00** [comment]
Thanks, removed the inactive ones. I kept normshield and urlvir for the time being as it seems they are still being updated but the method firehol uses to grab the lists are outdated, will keep an eye on it to see if things change.
