### ISSUE TITLE
WebUI not populating stats

### ISSUE THREAD

**Issue by jimcrapo** [Adamm00/IPSet_ASUS#40]
###### Brief Description Of Issue
The webui does not populate stats - shows "no data to display", despite having WebUI enabled.

Syslog & syslog-1 locations are set to default. 

###### Steps To Reproduce Issue
I have remediated this by going into settings (11 in the menu), then Display WebUI (14) and enabling, even though it was already enabled. This then seems to recreate the page (user2.asp) and regenerates the stats. 

###### Expected Behaviour
Graphical + lists of blocked addresses / sites.

###### Output of ( sh /jffs/scripts/firewall debug info )
Router Model; RT-AC3200
Skynet Version; v7.1.5 (10/04/2020) (2ab78437e26063032e6b950292a6c8c5)
iptables v1.4.15 - (eth0 @ x.x.x.x)
ipset v6.32, protocol version: 6
IP Address; (x.x.x.x) - (/)
FW Version; 384.13_6 (Apr 5 2020) (2.6.36.4brcmarm)
Install Dir; /tmp/mnt/sda1/skynet (11.3G / 14.2G Space Available)
SWAP File; /tmp/mnt/sda1/myswap.swp (2.0G)
Uptime; 0 days, 1 hours, 33 minutes.
Ram Available; (156M / 249M)

Internet-Connectivity               | [Passed]
Write Permission                    | [Passed]
Firewall-Start Entry                | [Passed]
Services-Stop Entry                 | [Passed]
Service-Event Entry                 | [Passed]
SWAP File                           | [Passed]
Cron Jobs                           | [Passed]
NTP Sync                            | [Passed]
IPSet Comment Support               | [Passed]
Log Level 7 Settings                | [Passed]
Duplicate Rules In RAW              | [Passed]
IPSets                              | [Passed]
IPTables Rules                      | [Passed]
Local WebUI Files                   | [Passed]
Mounted WebUI Files                 | [Passed]
MenuTree.js Entry                   | [Passed]

**Comment by Adamm00** [comment]
https://www.snbforums.com/threads/release-skynet-router-firewall-security-enhancements.16798/page-341#post-568024
