### ISSUE TITLE
Would you like to integrate IPSet_ASUS into project SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER

### ISSUE THREAD

**Issue by JACK-THINK** [Adamm00/IPSet_ASUS#42]
Hello,

I'm the owner and developer of the project [SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER](https://github.com/JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER). 

[Some users](https://github.com/JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER/issues/59) of my project and I really appreciate your **great job**. It would be **a great pleasure** if your awesome `SKYNET` could be integrated into project `SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER` which can be deployed on both ASUSWRT and ASUS-MERLIN. 

What's more, it's very convenient to integrated a program into SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER as an add-on as long as the program can run in shell. You can pick any add-on [here](https://github.com/JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER/tree/master/script_bootloader/usr) as a reference. SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER has already provided swap, entware, monit as the basis. The target is to make `Skynet` run perfectly on both ASUSWRT and ASUS-MERLIN.

Thanks a lot.

**Comment by Adamm00** [comment]
Skynet it heavily integrated into AsusWRT-Merlin and relies on features not available on stock models such as IPSet. 

Assuming you follow the standardized methods by other scriptwriters on this platform Skynet _should_ be compatible with most scripts out of the box.
