### ISSUE TITLE
Quick Q about WebUI

### ISSUE THREAD

**Issue by ninjada** [Adamm00/IPSet_ASUS#43]
###### Brief Description Of Issue
Assuming this hooks skynet functionality/stats into the default asus firmware webui?

Currently using asus merlin firmware, and installing via amtm, and don't see any skynet webui, or options for manual accesss. Assuming i should just disable webui under skynet settings?

**Comment by Adamm00** [comment]
What is the output of;

`firewall debug info`

If your settings are correct there should be a Skynet tab under the "firewall" heading in the WebUI

**Comment by ninjada** [comment]
Was probably my error, but i reinstalled and its appearing now. Thanks!
