### ISSUE TITLE
Skynet Blocking COD Warzone

### ISSUE THREAD

**Issue by killjoy2505** [Adamm00/IPSet_ASUS#45]
###### Brief Description Of Issue
Skynet Blocking COD Warzone Online Services since about 1 or 2 days

###### Steps To Reproduce Issue
Enable Skynet > COD Warzone cannot connect to online services

Disable Skynet > Can play Warzone perfectly fine.

Been troubleshooting this issue for a long time since I would not thought it would have to do with my router.

I cannot reply to any threads on SNB since I have a new account so I'd figured I'd post here.

**Comment by Adamm00** [comment]
https://github.com/Adamm00/IPSet_ASUS/wiki#applicationexe-or-websitecom-is-blocked

**Comment by killjoy2505** [comment]
I just want to let the author know. I have no further interest in using a firewall that is blocking legit applications.

**Comment by Adamm00** [comment]
Skynet blocks nothing by default. I don't maintain any of the example malware lists, they are provided by dozens of different well known sources. Users are free to use as many or few of them as they please, they are merely just an example for users to customize their own rules around. 

https://github.com/Adamm00/IPSet_ASUS/blob/master/filter.list

So its not the software "blocking legit applications" but instead the operator 😉
