### ISSUE TITLE
Skynet Not working anymore on RT-AC3200

### ISSUE THREAD

**Issue by doublefx** [Adamm00/IPSet_ASUS#46]
###### Brief Description Of Issue
I cannot not access Skynet anymore, I initially instaled it via amtm and it stops working, first it was showing cron job and others failed and then, black screen.

![image](https://user-images.githubusercontent.com/1222171/91537593-75990d00-e90e-11ea-94bb-c308e0ff0c03.png)

I tried to uninstall / Install with the same result, the issue is recent.

###### Steps To Reproduce Issue
Install Skynet on RT-AC3200 frw: 384.13_10

###### Expected Behaviour
Skynet to work

###### Output of ( sh /jffs/scripts/firewall debug info )
as shown in the screenshot

**Comment by Adamm00** [comment]
Please post the output of the following;

`sh -x /jffs/scripts/firewall debug info`

**Comment by doublefx** [comment]
![image](https://user-images.githubusercontent.com/1222171/91547756-45f10180-e91c-11ea-8702-5ada569c8b28.png)

**Comment by Adamm00** [comment]
During installation Skynet scans your attached USB's for conflicting scripts.

`		conflicting_scripts="(IPSet_Block.sh|malware-filter|privacy-filter|ipBLOCKer.sh|ya-malware-block.sh|iblocklist-loader.sh|firewall-reinstate.sh)$"
		if find /jffs /tmp/mnt | grep -qE "$conflicting_scripts"; then
			echo "[*] $(find /jffs /tmp/mnt | grep -E "$conflicting_scripts" | xargs) Detected - This Script Will Cause Conflicts! Please Remove Immediately."
			echo
		fi`

I assume you have a large slow HDD attached so this may take some time to complete. Your best bet is to just let Skynet do its thing and come back to it later once the scan is complete then continue with the installation.

**Comment by doublefx** [comment]
Hi Adam, Skynet is still at the same point after 2 days, what should I do?

**Comment by Adamm00** [comment]
Update skynet to the latest version, I recently removed this check as it is no longer as necessary as it once was due to the incompatible scripts no longer being maintained

**Comment by doublefx** [comment]
What the best way to do that manually given it does not respond thru amtm

**Comment by Adamm00** [comment]
`/usr/sbin/curl -s "https://raw.githubusercontent.com/Adamm00/IPSet_ASUS/master/firewall.sh" -o "/jffs/scripts/firewall" && chmod 755 /jffs/scripts/firewall && sh /jffs/scripts/firewall install`

**Comment by doublefx** [comment]
It looks all good now, many thanks.

And you was right indeed, I have a large USB HDD connected to the router.
