### ISSUE TITLE
Adding List

### ISSUE THREAD

**Issue by scafroglia93** [Adamm00/IPSet_ASUS#48]
Is it possible to insert the following lists even if they are not included in firehol?

Italian CERT ->
https://infosec.cert-pa.it/analyze/listip.txt

**Comment by Adamm00** [comment]
Yes, its as simple as hosting your own filter list on a website like pastebin and adding this IP list to the bottom of it;

Example filter list;
https://github.com/Adamm00/IPSet_ASUS/blob/master/filter.list

**Comment by scafroglia93** [comment]
can you explian me better please
