### ISSUE TITLE
Cert Italian IoC

### ISSUE THREAD

**Issue by scafroglia93** [Adamm00/IPSet_ASUS#49]
It would be possible to insert it by default, it is managed by the Italian government

https://infosec.cert-pa.it/analyze/listip.txt

It would be possible to insert it by default, it is managed by the Italian government

Thanks

**Comment by Adamm00** [comment]
#48 

This can be done manually by using a custom malware filter as per the readme;

`( firewall banmalware google.com/filter.list ) This Uses The Filter List From The Specified URL`
