### ISSUE TITLE
duplicate Skynet tabs after restart of Skynet via cmd line 

### ISSUE THREAD

**Issue by joalmjoalm** [Adamm00/IPSet_ASUS#50]
###### Brief Description Of Issue
duplicate Skynet tab generated in the firewall page when restarted skynet in the cmd line

###### Steps To Reproduce Issue
Asus 68U
Asus merlin 384.19
Skynet installed via amtm
first tab appears in the fw menu
via amtm, open skynet cmd line and choose restart skynet
a second Skynet tab appears with valid info

###### Expected Behaviour
remove first tab when restarting

**Comment by Adamm00** [comment]
Can't reproduce this on my end. The easiest way to fix duplicate tabs for any script is just a simple reboot.
