### ISSUE TITLE
Old support forum broken

### ISSUE THREAD

**Issue by Audionut** [Adamm00/IPSet_ASUS#53]
Hi,

The old support forum is broken. The link in the about section directs to a closed thread and it is apparent that the developer is no longer, at this stage at least, using that forum as a method of support.

Are there other places on the web where the community can interact with the developer and each other? Is there a discord channel?

**Comment by Adamm00** [comment]
Any issues etc can be posted here on the issue tracker and will be looked at. I unfortunately in good faith cannot support the decisions being made over at said forum as they have significantly made things worse for developers.

**Comment by nlurker** [comment]
@Adamm00, this might be a good snb replacement for open discussions:

https://docs.github.com/en/free-pro-team@latest/discussions
