### ISSUE TITLE
api.hackertarget.com is rate limiting. Custom user agent needed?

### ISSUE THREAD

**Issue by dave14305** [Adamm00/IPSet_ASUS#54]
###### Brief Description Of Issue
CDN Whitelisting is failing for some users due to "API count exceeded - Increase Quota with Membership" errors.

###### Steps To Reproduce Issue
https://www.snbforums.com/threads/paypal-is-being-blocked.67744/page-2#post-633865

###### Expected Behaviour
Add custom random user agent to the curl command in Whitelist_CDN() ? Maybe ?

**Comment by Adamm00** [comment]
Not sure what someone must have done to get rate limited as you get 500(?) lookups per day on hackertarget, but in any case I've switched to bgpview.io as they don't seem to have any sort of API limits.

**Comment by dave14305** [comment]
> they don't seem to have any sort of API limits.

Yet. :)

**Comment by jumpsmm7** [comment]
Too bad you can't have some sort of API roll-over (basically a backup link for if one fails) incase there ever is an API limit.

**Comment by Adamm00** [comment]
> Too bad you can't have some sort of API roll-over (basically a backup link for if one fails) incase there ever is an API limit.

That is the plan if bgpview start rate limiting us, I would have done it already but it makes our loop code ugly.
