### ISSUE TITLE
whitelist MAC

### ISSUE THREAD

**Issue by kurktchiev** [Adamm00/IPSet_ASUS#55]
###### Brief Description Of Issue
I am trying to figure out if there is a way to whitelist based on MAC address rather than IP. I keep getting blocked to my home router by Skynet when I come in from overseas for work, and obviously my IP changes all the time, but my MAC doesn't, so if I could whitelist based on that... I think I will stop running into this :(

**Comment by Adamm00** [comment]
Unfortunately there is no current way to whitelist via mac address. 

If your remote IP's are already blacklisted your best bet would be to either adjust your malware list accordingly or if using mobile data keep toggling it on/off until you're assigned an IP that isn't flagged.
