### ISSUE TITLE
Recommendation for false positive firehol 3 ipset

### ISSUE THREAD

**Issue by agilani0101** [Adamm00/IPSet_ASUS#56]
###### Brief Description Of Issue
At least 4 or 5 times over the past month firehol level 3 ipset had bad entries in it.  What is the recommendation to remedy this?  Add addresses to whitelist or try to report to firehol (which i couldn't find).

**Comment by Adamm00** [comment]
We have no control over the content of each list. Firehol3 in particular is a bunch of different lists aggregated so you would need to track down where false positives originated from and report them to their maintainers;

https://iplists.firehol.org/?ipset=firehol_level3
