### ISSUE TITLE
arithmetic syntax error

### ISSUE THREAD

**Issue by Audionut** [Adamm00/IPSet_ASUS#57]
No changes to the router in the last few days, everything seemingly running fine, then logged in today to see this error.

/jffs/scripts/firewall: line 40: arithmetic syntax error

Not sure how to.....

**Comment by Audionut** [comment]
Oh wait....

`Audionut@RT-AX88U-E188:/tmp/home/root# sh /jffs/scripts/firewall debug info
#############################################################################################################
#                                                                                                           #
#                  ███████╗██╗  ██╗██╗   ██╗███╗   ██╗███████╗████████╗    ██╗   ██╗███████╗                #
#                  ██╔════╝██║ ██╔╝╚██╗ ██╔╝████╗  ██║██╔════╝╚══██╔══╝    ██║   ██║╚════██║                #
#                  ███████╗█████╔╝  ╚████╔╝ ██╔██╗ ██║█████╗     ██║       ██║   ██║    ██╔╝                #
#                  ╚════██║██╔═██╗   ╚██╔╝  ██║╚██╗██║██╔══╝     ██║       ╚██╗ ██╔╝   ██╔╝                 #
#                  ███████║██║  ██╗   ██║   ██║ ╚████║███████╗   ██║        ╚████╔╝    ██║                  #
#                  ╚══════╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝╚══════╝   ╚═╝         ╚═══╝     ╚═╝                  #
#                                                                                                           #
#                                 Router Firewall And Security Enhancements                                 #
#                             By Adamm -  https://github.com/Adamm00/IPSet_ASUS                             #
#                                            19/11/2020 - v7.2.3                                            #
#############################################################################################################


=============================================================================================================


Router Model;
Skynet Version;  (19/11/2020) (d54b1aeafe718d39a56c68794b36fdeb)
iptables v1.4.15 - (eth0 @ 192.168.50.1)
ipset v6.32, protocol version: 6
IP Address; (87.121.72.84)
FW Version; 384.18_beta1 (Jun 19 2020) (4.1.51)
Install Dir; /tmp/mnt/router/skynet (11.3G / 14.1G Space Available)
Syslog Location; () ()
Uptime; 1 days, 10 hours, 59 minutes.
Ram Available; (465M / 882M)


---------------                          | ------------     | ---------------      | ----------
| Device Name |                          | | Local IP |     | | MAC Address |      | | Status |
---------------                          | ------------     | ---------------      | ----------

Unknown                                  | 87.121.72.1      | 64:d1:54:3b:4a:f9    | Online
Unknown                                  | 87.121.72.2      | 00:00:5e:80:00:01    | Inactive
Unknown                                  | 192.168.50.29    | Unknown              | Offline
LAPTOP-DF95VU7N                          | 192.168.50.54    | dc:f5:05:21:0b:25    | Inactive
S10                                      | 192.168.50.122   | 7e:2b:72:29:6e:46    | Inactive
Z6621O                                   | 192.168.50.123   | Unknown              | Offline
Unknown                                  | 192.168.50.171   | 80:9f:9b:39:b3:1a    | Inactive
PS5_wifi                                 | 192.168.50.179   | 1c:98:c1:4a:84:33    | Inactive
Jtablet                                  | 192.168.50.205   | f0:ee:10:73:76:5e    | Inactive
Jtv                                      | 192.168.50.215   | c8:3a:6b:ea:e0:50    | Online
DESKTOP-76JL9A3                          | 192.168.50.239   | 70:85:c2:72:07:40    | Online


--------------------                | ----------
| Test Description |                | | Result |
--------------------                | ----------

Internet-Connectivity               | [Passed]
Write Permission                    | [Passed]
Config File                         | [Passed]
Firewall-Start Entry                | [Passed]
Services-Stop Entry                 | [Passed]
Service-Event Entry                 | [Passed]
Profile.add Entry                   | [Passed]
SWAP File                           | [Passed]
Cron Jobs                           | [Passed]
NTP Sync                            | [Passed]
IPSet Comment Support               | [Passed]
Log Level 5 Settings                | [Passed]
Duplicate Rules In RAW              | [Passed]
IPSets                              | [Passed]
IPTables Rules                      | [Passed]


-----------                         | ----------
| Setting |                         | | Status |
----------                          | ----------

Skynet Auto-Updates                 | [Disabled]
Malware List Auto-Updates           | [Disabled]
Logging                             | [Disabled]
Filter Traffic                      | [Selective]
Unban PrivateIP                     | [Disabled]
Log Invalid Packets                 | [Disabled]
Import AiProtect Data               | [Disabled]
Secure Mode                         | [Disabled]
Fast Switch List                    | [Disabled]
Syslog Location                     | [Custom]
IOT Blocking                        | [Disabled]
Country Lookup For Stats            | [Disabled]
CDN Whitelisting                    | [Disabled]
Display WebUI                       | [Disabled]

15/15 Tests Sucessful


=============================================================================================================


/jffs/scripts/firewall: line 5686: arithmetic syntax error
Audionut@RT-AX88U-E188:/tmp/home/root#`

**Comment by Adamm00** [comment]
Your Skynet config file is missing, I suggest running the install command to see if that corrects it otherwise this may indicate a failing USB. Also you may want to update your firmware version.

**Comment by Audionut** [comment]
Install command fixed it, and automatically picked up my custom filter list and whitelisted entries. Will monitor the USB. Cheers.
