### ISSUE TITLE
Port Blocking - Gaming

### ISSUE THREAD

**Issue by RickBankers** [Adamm00/IPSet_ASUS#58]
Also, since the last skynet update I am unable to connect to some battlefield 4 servers. It seems specific to skynet because when I disable skynet things work. Once I enable it things are broken again. I added some port forwarding inside of the Asus router and that didnt seem to fix it. The only solution is disabling skynet which is something I prefer not to do.

**Comment by Adamm00** [comment]
What is the output of;

`firewall debug info`

**Comment by Adamm00** [comment]
As for battlefield being blocked, follow this guide to whitelist the IP in question;

https://github.com/Adamm00/IPSet_ASUS/wiki#applicationexe-or-websitecom-is-blocked

**Comment by RickBankers** [comment]
Interestingly it just started working today without any changes to skynet. Very odd behavior. If I run into it again I'll be sure to check the firewall debug info.
