### ISSUE TITLE
What routers does Skynet work on?

### ISSUE THREAD

**Issue by whisperdancer** [Adamm00/IPSet_ASUS#60]
I am using an Asus AC56U and Skynet works fine. I'm considering updating my modem to a new Asus model as Merlin no longer supports updates to my router. I noticed this from an older post in 2014: 
_For now support is limited to the AC56U and AC68U. Sorry about that._

As that post is many years old I am curious if other routers have since been added to the list of supported routers. Can you please list which Asus routers can currently run Skynet.

Many Thanks!

**Comment by Adamm00** [comment]
> I am using an Asus AC56U and Skynet works fine. I'm considering updating my modem to a new Asus model as Merlin no longer supports updates to my router. I noticed this from an older post in 2014:
> _For now support is limited to the AC56U and AC68U. Sorry about that._
> 
> As that post is many years old I am curious if other routers have since been added to the list of supported routers. Can you please list which Asus routers can currently run Skynet.
> 
> Many Thanks!

Skynet supports all routers that are currently supported by Merlins firmware.
