### ISSUE TITLE
Ban does not work

### ISSUE THREAD

**Issue by parentol** [Adamm00/IPSet_ASUS#62]
###### Brief Description Of Issue
Sorry for the very basic issue but I can't seem to make the ban command work. I know it's probably my setup but I need some help to find out why it's not working...

Thanks in advance

###### Steps To Reproduce Issue
I'm entering the following command

firewall ban domain 25stanley.com

getting this as output

[i] Adding 25stanley.com To Blacklist
[i] Banning 104.26.5.69
[i] Banning 104.26.4.69
[i] Banning 172.67.75.56
[i] Saving Changes

But all the devices connected to my network can still access the web site without being blocked. 

###### Expected Behaviour
Outbound access to the domain should be blocked.

###### Output of ( sh /jffs/scripts/firewall debug info )
Router Model; RT-AC86U
Skynet Version; v7.2.3 (01/12/2020) (358a0e65e85afa8425897a993eb84b8c)
iptables v1.4.15 - (ppp0 @ XXXXXXXXXX)
ipset v6.32, protocol version: 6
IP Address; (XXXXXXXX)
FW Version; 384.19_0 (Aug 14 2020) (4.1.27)
Install Dir; /tmp/mnt/SONY16GB/skynet (11.4G / 14.2G Space Available)
SWAP File; /tmp/mnt/SONY16GB/myswap.swp (2.0G)
Banned Countries; cn br ir ua ar iq tw th lv ru ro cl sa pk bg
Uptime; 0 days, 1 hours, 2 minutes.
Ram Available; (108M / 430M)

--------------------                | ----------
| Test Description |                | | Result |
--------------------                | ----------

Internet-Connectivity               | [Passed]
Write Permission                    | [Passed]
Config File                         | [Passed]
Firewall-Start Entry                | [Passed]
Services-Stop Entry                 | [Passed]
Service-Event Entry                 | [Passed]
Profile.add Entry                   | [Passed]
SWAP File                           | [Passed]
Cron Jobs                           | [Passed]
NTP Sync                            | [Passed]
IPSet Comment Support               | [Passed]
Log Level 5 Settings                | [Passed]
Duplicate Rules In RAW              | [Passed]
IPSets                              | [Passed]
IPTables Rules                      | [Passed]
Local WebUI Files                   | [Passed]
Mounted WebUI Files                 | [Passed]
MenuTree.js Entry                   | [Passed]

-----------                         | ----------
| Setting |                         | | Status |
----------                          | ----------

Skynet Auto-Updates                 | [Enabled]
Malware List Auto-Updates           | [Enabled]
Logging                             | [Enabled]
Filter Traffic                      | [Enabled]
Unban PrivateIP                     | [Enabled]
Log Invalid Packets                 | [Disabled]
Import AiProtect Data               | [Disabled]
Secure Mode                         | [Enabled]
Fast Switch List                    | [Disabled]
Syslog Location                     | [Default]
IOT Blocking                        | [Disabled]
Country Lookup For Stats            | [Enabled]
CDN Whitelisting                    | [Enabled]
Display WebUI                       | [Enabled]

18/18 Tests Sucessful

**Comment by Adamm00** [comment]
> ###### Brief Description Of Issue
> Sorry for the very basic issue but I can't seem to make the ban command work. I know it's probably my setup but I need some help to find out why it's not working...
> 
> Thanks in advance
> 
> ###### Steps To Reproduce Issue
> I'm entering the following command
> 
> firewall ban domain 25stanley.com
> 
> getting this as output
> 
> [i] Adding 25stanley.com To Blacklist
> [i] Banning 104.26.5.69
> [i] Banning 104.26.4.69
> [i] Banning 172.67.75.56
> [i] Saving Changes
> 
> But all the devices connected to my network can still access the web site without being blocked.
> 
> ###### Expected Behaviour
> Outbound access to the domain should be blocked.
> 
> ###### Output of ( sh /jffs/scripts/firewall debug info )
> Router Model; RT-AC86U
> Skynet Version; v7.2.3 (01/12/2020) (358a0e65e85afa8425897a993eb84b8c)
> iptables v1.4.15 - (ppp0 @ XXXXXXXXXX)
> ipset v6.32, protocol version: 6
> IP Address; (XXXXXXXX)
> FW Version; 384.19_0 (Aug 14 2020) (4.1.27)
> Install Dir; /tmp/mnt/SONY16GB/skynet (11.4G / 14.2G Space Available)
> SWAP File; /tmp/mnt/SONY16GB/myswap.swp (2.0G)
> Banned Countries; cn br ir ua ar iq tw th lv ru ro cl sa pk bg
> Uptime; 0 days, 1 hours, 2 minutes.
> Ram Available; (108M / 430M)
> 
> -------------------- | ----------
> | Test Description | | | Result |
> -------------------- | ----------
> 
> Internet-Connectivity | [Passed]
> Write Permission | [Passed]
> Config File | [Passed]
> Firewall-Start Entry | [Passed]
> Services-Stop Entry | [Passed]
> Service-Event Entry | [Passed]
> Profile.add Entry | [Passed]
> SWAP File | [Passed]
> Cron Jobs | [Passed]
> NTP Sync | [Passed]
> IPSet Comment Support | [Passed]
> Log Level 5 Settings | [Passed]
> Duplicate Rules In RAW | [Passed]
> IPSets | [Passed]
> IPTables Rules | [Passed]
> Local WebUI Files | [Passed]
> Mounted WebUI Files | [Passed]
> MenuTree.js Entry | [Passed]
> 
> ----------- | ----------
> | Setting | | | Status |
> ---------- | ----------
> 
> Skynet Auto-Updates | [Enabled]
> Malware List Auto-Updates | [Enabled]
> Logging | [Enabled]
> Filter Traffic | [Enabled]
> Unban PrivateIP | [Enabled]
> Log Invalid Packets | [Disabled]
> Import AiProtect Data | [Disabled]
> Secure Mode | [Enabled]
> Fast Switch List | [Disabled]
> Syslog Location | [Default]
> IOT Blocking | [Disabled]
> Country Lookup For Stats | [Enabled]
> CDN Whitelisting | [Enabled]
> Display WebUI | [Enabled]
> 
> 18/18 Tests Sucessful

What is the output of;

`firewall stats search ip 104.26.5.69`

**Comment by parentol** [comment]
Hello Adamm,

Thanks for the quick response! Really love your Skynet!!

So there's something whitelisting the address..... Odd...

104.26.5.15 "Shared-Whitelist: api.db-ip.com"

Should I remove the Whitelist entry ? It will probably block other addresses I don't want to be banned... 

Complete Output :

[i] Logging Data Detected in /tmp/mnt/SONY16GB/skynet/skynet.log - 4.1M
[i] Monitoring From Jan 26 15:00:09 To Jan 28 07:47:52
[i] 17620 Block Events Detected
[i] 1886 Unique IPs
[i] 7 Manual Bans Issued

104.26.5.69 is in set Skynet-Whitelist.
104.26.5.69 is in set Skynet-Blacklist.
104.26.5.69 is NOT in set Skynet-BlockedRanges.

Whitelist Reason;
 104.26.5.15 "Shared-Whitelist: api.db-ip.com"

Blacklist Reason;
 "ManualBanD: 25stanley.com"


[i] IP Location - United States (CLOUDFLARENET / AS13335)

[i] 104.26.5.69 First Tracked On
[i] 104.26.5.69 Last Tracked On
[i] 0 Blocks Total

Event Log Entries From 104.26.5.69;
Jan 27 18:27:41 Skynet: [Manual Ban] TYPE=Domain SRC=104.26.5.69 Host=25stanley

First Block Tracked From 104.26.5.69;
*--
10 Most Recent Blocks From 104.26.5.69;


Top 10 Targeted Ports From 104.26.5.69 (Inbound);


--------   | --------   | --------------
| Hits |   | | Port |   | | SpeedGuide |
--------   | --------   | --------------

-*-

Top 10 Sourced Ports From 104.26.5.69 (Inbound);


--------   | --------   | --------------
| Hits |   | | Port |   | | SpeedGuide |
--------   | --------   | --------------

--*


================================================================================

**Comment by parentol** [comment]
Quick question : Shouldn't the blacklist entry have precedence over the whitelist entry ?

**Comment by Adamm00** [comment]
> Quick question : Shouldn't the blacklist entry have precedence over the whitelist entry ?

The whitelist takes priority. The entry in question is whitelisted due to it sharing an IP with a provider we use for IP lookup information.

**Comment by parentol** [comment]
May I suggest that manual ban entris should override any whitelist ones? How can I make the ban work without breaking your ip lookup?
