### ISSUE TITLE
Error in skynet log "/jffs/scripts/firewall: line 5682: [: Argument list too long:

### ISSUE THREAD

**Issue by tmlgcq** [Adamm00/IPSet_ASUS#63]
###### Brief Description Of Issue
Noted the following error occasionally repeating in my skynet logs. Googled but, did not find anything specific:

skynet /jffs/scripts/firewall: line 5682: [: Argument list too long

###### Steps To Reproduce Issue
None - Simply running Skynet.

###### Expected Behaviour
Error should not bee seen.

###### Output of ( sh /jffs/scripts/firewall debug info )
#                                 Router Firewall And Security Enhancements    #
#                             By Adamm -  https://github.com/Adamm00/IPSet_ASUS#
#                                            01/12/2020 - v7.2.3               #

================================================================================
Router Model; RT-AC5300
Skynet Version; v7.2.3 (01/12/2020) (358a0e65e85afa8425897a993eb84b8c)
iptables v1.4.15 - (eth0 @ 192.168.1.1)
ipset v6.32, protocol version: 6
IP Address; (73.227.230.247)
FW Version; 384.19_0 (Aug 14 2020) (2.6.36.4brcmarm)
Install Dir; /tmp/mnt/ENTWARE/skynet (50.9G / 56.4G Space Available)
SWAP File; /tmp/mnt/ENTWARE/myswap.swp (2.0G)
Syslog Location; (/opt/var/log/skynet-0.log) (/tmp/syslog.log-1)
Banned Countries; cn ru sc ua ee ls gr bg hr cz ge hu kg lv lt mc kp ro sk vn uk
Uptime; 15 days, 13 hours, 5 minutes.
Ram Available; (102M / 503M)

---------------                          | ------------     | ---------------   
| Device Name |                          | | Local IP |     | | MAC Address |   
---------------                          | ------------     | ---------------   

REMOVED

--------------------                | ----------
| Test Description |                | | Result |
--------------------                | ----------

Internet-Connectivity               | [Passed]
Write Permission                    | [Passed]
Config File                         | [Passed]
Firewall-Start Entry                | [Passed]
Services-Stop Entry                 | [Passed]
Service-Event Entry                 | [Passed]
Profile.add Entry                   | [Passed]
SWAP File                           | [Passed]
Cron Jobs                           | [Passed]
NTP Sync                            | [Passed]
IPSet Comment Support               | [Passed]
Log Level 5 Settings                | [Passed]
Duplicate Rules In RAW              | [Passed]
IPSets                              | [Passed]
IPTables Rules                      | [Passed]
Local WebUI Files                   | [Passed]
Mounted WebUI Files                 | [Passed]
MenuTree.js Entry                   | [Passed]

-----------                         | ----------
| Setting |                         | | Status |
----------                          | ----------

Skynet Auto-Updates                 | [Enabled]
Malware List Auto-Updates           | [Enabled]
Logging                             | [Enabled]
Filter Traffic                      | [Enabled]
Unban PrivateIP                     | [Enabled]
Log Invalid Packets                 | [Enabled]
Import AiProtect Data               | [Enabled]
Secure Mode                         | [Enabled]
Fast Switch List                    | [Disabled]
Syslog Location                     | [Custom]
IOT Blocking                        | [Disabled]
Country Lookup For Stats            | [Enabled]
CDN Whitelisting                    | [Enabled]
Display WebUI                       | [Enabled]

18/18 Tests Sucessful              

================================================================================

[#] 52609 IPs (+0) -- 36158 Ranges Banned (+0) || 199 Inbound -- 1 Outbound Con]

**Comment by Adamm00** [comment]
Your going to need to show an example of precisely when this error occurs, otherwise there is no way I can figure out whats actually happening.

**Comment by Adamm00** [comment]
Going to close this as you haven’t responded in 2 weeks
