### ISSUE TITLE
ax88u ram 99%

### ISSUE THREAD

**Issue by dbb12345** [Adamm00/IPSet_ASUS#64]
###### Brief Description Of Issue
within a minute or 2 of installing skynet my ram goes from 50% to 99%

###### Steps To Reproduce Issue
install and turn on skynet (diversion already up and running)

###### Expected Behaviour
few mbs

###### Output of ( sh /jffs/scripts/firewall debug info )
point me to what you need and i can provide.. just started after recent merlin update

**Comment by Adamm00** [comment]
https://www.linuxatemyram.com/
