### ISSUE TITLE
Blocking github.com

### ISSUE THREAD

**Issue by yahwehPT** [Adamm00/IPSet_ASUS#65]
###### Brief Description Of Issue
I'm having problems accessing github.com

###### Output of ( sh /jffs/scripts/firewall debug info )
asusvilar@router:/tmp/home/root# sh /jffs/scripts/firewall debug info
#############################################################################################################
#                                 Router Firewall And Security Enhancements                                 #
#                             By Adamm -  https://github.com/Adamm00/IPSet_ASUS                             #
#                                            12/03/2021 - v7.2.4                                            #
#############################################################################################################

=============================================================================================================

Router Model; RT-AC86U
Skynet Version; v7.2.4 (12/03/2021) (5108beaccd8af56c50682d2253e66320)
iptables v1.4.15 - (eth0 @ 192.168.3.1)
ipset v7.6, protocol version: 7
IP Address; ()
FW Version; 386.2_beta1 (Mar 10 2021) (4.1.27)
Install Dir; /tmp/mnt/Router/skynet (101.8G / 109.5G Space Available)
SWAP File; /tmp/mnt/Router/myswap.swp (2.0G)
Syslog Location; (/opt/var/log/skynet-0.log) (/tmp/syslog.log-1)
Uptime; 0 days, 7 hours, 38 minutes.
Ram Available; (50M / 430M)

---------------                          | ------------     | ---------------      | ----------
| Device Name |                          | | Local IP |     | | MAC Address |      | | Status |
---------------                          | ------------     | ---------------      | ----------

Unknown                                  | 81.193.62.1      | 00:03:fa:00:00:01    | Online
Desktop-Server                           | 192.168.3.4      | a8:5e:45:e4:c2:c3    | Online
Unknown                                  | 192.168.3.5      | 58:82:a8:9b:e5:c4    | Online
DESKTOP-TN7C9BK                          | 192.168.3.6      | Unknown              | Offline
RT-AC86U-C3E8                            | 192.168.3.99     | 24:4b:fe:bd:c3:e8    | Online
Unknown                                  | 192.168.3.107    | c8:28:32:2c:2c:18    | Online
Unknown                                  | 192.168.3.115    | 3c:2a:f4:b4:0c:84    | Inactive
AppleWadeSergio                          | 192.168.3.118    | ea:e7:65:a9:4c:d3    | Inactive
HarmonyHub                               | 192.168.3.145    | 00:04:20:e7:de:29    | Online
Unknown                                  | 192.168.3.159    | 98:d6:bb:27:99:d2    | Inactive
Unknown                                  | 192.168.3.173    | 00:04:4b:48:6c:d4    | Online
Google-Home-Mini                         | 192.168.3.175    | e4:f0:42:1a:9f:84    | Online
iPhone                                   | 192.168.3.182    | 26:4e:59:07:5b:91    | Inactive
Tablet Julia                             | 192.168.3.183    | 00:0a:f5:b0:18:b4    | Online
Galaxy-A70                               | 192.168.3.184    | Unknown              | Offline
Denon-AVR-X2400H                         | 192.168.3.189    | 00:05:cd:e3:1d:50    | Online
LGwebOSTV                                | 192.168.3.194    | Unknown              | Offline
assistant                                | 192.168.3.199    | 28:c2:dd:ef:87:95    | Inactive
Assistant-PLG                            | 192.168.3.200    | 80:7d:3a:02:15:4e    | Inactive
Termoacumulador                          | 192.168.3.205    | e0:98:06:b4:ff:20    | Inactive
Escritorio                               | 192.168.3.206    | e0:98:06:ab:95:2e    | Inactive
Quarto-J                                 | 192.168.3.207    | e0:98:06:97:7b:a4    | Inactive
Shelly H&T                               | 192.168.3.208    | 84:cc:a8:ad:06:cf    | Inactive
Amplificador                             | 192.168.3.210    | e0:98:06:9a:53:69    | Inactive
Amplificador                             | 192.168.3.211    | 80:7d:3a:02:13:ce    | Inactive
EM-1                                     | 192.168.3.227    | ec:fa:bc:c7:f3:e7    | Inactive
EM-2                                     | 192.168.3.228    | 68:c6:3a:f9:5b:6a    | Inactive

--------------------                | ----------
| Test Description |                | | Result |
--------------------                | ----------

Internet-Connectivity               | [Passed]
Write Permission                    | [Passed]
Config File                         | [Passed]
Firewall-Start Entry                | [Passed]
Services-Stop Entry                 | [Passed]
Service-Event Entry                 | [Passed]
Profile.add Entry                   | [Passed]
SWAP File                           | [Passed]
Cron Jobs                           | [Passed]
NTP Sync                            | [Passed]
IPSet Comment Support               | [Passed]
Log Level 5 Settings                | [Passed]
Duplicate Rules In RAW              | [Passed]
IPSets                              | [Passed]
IPTables Rules                      | [Passed]
Local WebUI Files                   | [Passed]
Mounted WebUI Files                 | [Passed]
MenuTree.js Entry                   | [Passed]

-----------                         | ----------
| Setting |                         | | Status |
----------                          | ----------

Skynet Auto-Updates                 | [Enabled]
Malware List Auto-Updates           | [Enabled]
Logging                             | [Enabled]
Filter Traffic                      | [Enabled]
Unban PrivateIP                     | [Enabled]
Log Invalid Packets                 | [Disabled]
Import AiProtect Data               | [Enabled]
Secure Mode                         | [Enabled]
Fast Switch List                    | [Disabled]
Syslog Location                     | [Custom]
IOT Blocking                        | [Enabled]
Country Lookup For Stats            | [Enabled]
CDN Whitelisting                    | [Enabled]
Display WebUI                       | [Enabled]

18/18 Tests Sucessful

=============================================================================================================

[#] 45755 IPs (+0) -- 1625 Ranges Banned (+0) || 79 Inbound -- 66 Outbound Connections Blocked! [debug] [2s]

asusvilar@router:/tmp/home/root#

and

asusvilar@router:/tmp/home/root# firewall stats search ip 140.82.121.4
#############################################################################################################
#                                 Router Firewall And Security Enhancements                                 #
#                             By Adamm -  https://github.com/Adamm00/IPSet_ASUS                             #
#                                            12/03/2021 - v7.2.4                                            #
#############################################################################################################

=============================================================================================================

[i] Logging Data Detected in /tmp/mnt/Router/skynet/skynet.log - 2.4M
[i] Monitoring From Mar 15 17:53:46 To Mar 16 22:42:07
[i] 8912 Block Events Detected
[i] 1700 Unique IPs
[i] 0 Manual Bans Issued

Warning: 140.82.121.4 is in set Skynet-Whitelist.
Warning: 140.82.121.4 is in set Skynet-Blacklist.
140.82.121.4 is NOT in set Skynet-BlockedRanges.

Whitelist Reason;
 140.82.121.4 "ManualWlistD: github.com"

Blacklist Reason;
 "BanMalware: firehol_level3.netset"

[i] IP Location - Netherlands (GITHUB / AS36459)

[i] 140.82.121.4 First Tracked On
[i] 140.82.121.4 Last Tracked On
[i] 0 Blocks Total

Event Log Entries From 140.82.121.4;
Mar 16 22:41:03 Skynet: [Manual Whitelist] TYPE=Domain SRC=140.82.121.4 Host=github.com

First Block Tracked From 140.82.121.4;
--*
10 Most Recent Blocks From 140.82.121.4;

Top 10 Targeted Ports From 140.82.121.4 (Inbound);

--------   | --------   | --------------
| Hits |   | | Port |   | | SpeedGuide |
--------   | --------   | --------------

Top 10 Sourced Ports From 140.82.121.4 (Inbound);

--------   | --------   | --------------
| Hits |   | | Port |   | | SpeedGuide |
--------   | --------   | --------------

*--

=============================================================================================================

[#] 45755 IPs (+0) -- 1625 Ranges Banned (+0) || 74 Inbound -- 66 Outbound Connections Blocked! [stats] [3s]

I had to manually add to whitelist. Probably have to report to the list owners and not here but I also have some problems since last update and do not know if it has something to do with github being blocked: stats sometimes don't generate and I don't have a clue how to debug, could you please help?
thank you

**Comment by itsJarrett** [comment]
Must be an issue with that iplist.

I am sure db administrators for that list are aware as we are not the only ones using that list.

**Comment by buberj** [comment]
Had the same issue, but it just resolved itself. github.com seems to have moved to a "neighboring" IP - 140.82.121.3 and thankfully it is not on the firehol_level3. In any case this is not a Skynet issue
