### ISSUE TITLE
IPs do not get blocked correctly 

### ISSUE THREAD

**Issue by ssafhi** [Adamm00/IPSet_ASUS#66]
First of all, Thank you so much for your hard work on this awesome project.

 ###### Brief Description Of Issue

Hello, I have an issue with the Skynet firewall everything working fine when I block an IP, the IP gets blocked and the pinging stopped. 
I'm trying to block a specific IP server in a game so I don't connect to that server, because the latency is too high on it, but after blocking the IP when I’m pinging the server IP in cmd I got Request timed out which means it’s blocked by Skynet, but in the game, the server doesn't get blocked and still get connected to that server.

I tried to use Peerblock to block the IP it gets blocked correctly.

###### Steps To Reproduce Issue

logged to ssh
firewall
2
1
entered the IP and name
no ping from cmd
but I can connect to the game server

###### Expected Behaviour

can't connect to the game server

###### Output of ( sh /jffs/scripts/firewall debug info )

Router Model; RT-AC86U
Skynet Version; v7.2.4 (12/03/2021) (5108beaccd8af56c50682d2253e66320)
iptables v1.4.15 - (ppp0 @ 192.168.1.1)
ipset v7.6, protocol version: 7
IP Address; (1.1.1.1)
FW Version; 386.2_beta1 (Mar 10 2021) (4.1.27)
Install Dir; /tmp/mnt/sda1/skynet (26.6G / 28.6G Space Available)
SWAP File; /tmp/mnt/sda1/myswap.swp (2.0G)
Banned Countries; uk
Uptime; 1 days, 13 hours, 13 minutes.
Ram Available; (101M / 430M)

---------------                          | ------------     | ---------------      | ----------
| Device Name |                          | | Local IP |     | | MAC Address |      | | Status |
---------------                          | ------------     | ---------------      | ----------

S21                                      | 192.168.1.21     | f6:***********:f5    | Inactive
Unknown                                  | 192.168.1.85     | 48:***********:6b    | Online
Unknown                                  | 192.168.1.150    | 18:***********:3f    | Online
Unknown                                  | 192.168.1.151    | Unknown              | Offline

--------------------                | ----------
| Test Description |                | | Result |
--------------------                | ----------

Internet-Connectivity               | [Passed]
Write Permission                    | [Passed]
Config File                         | [Passed]
Firewall-Start Entry                | [Passed]
Services-Stop Entry                 | [Passed]
Service-Event Entry                 | [Passed]
Profile.add Entry                   | [Passed]
SWAP File                           | [Passed]
Cron Jobs                           | [Passed]
NTP Sync                            | [Passed]
IPSet Comment Support               | [Passed]
Log Level 5 Settings                | [Passed]
Duplicate Rules In RAW              | [Passed]
IPSets                              | [Passed]
IPTables Rules                      | [Passed]
Local WebUI Files                   | [Failed]
Mounted WebUI Files                 | [Failed]
MenuTree.js Entry                   | [Passed]

-----------                         | ----------
| Setting |                         | | Status |
----------                          | ----------

Skynet Auto-Updates                 | [Enabled]
Malware List Auto-Updates           | [Enabled]
Logging                             | [Enabled]
Filter Traffic                      | [Enabled]
Unban PrivateIP                     | [Disabled]
Log Invalid Packets                 | [Disabled]
Import AiProtect Data               | [Disabled]
Secure Mode                         | [Enabled]
Fast Switch List                    | [Disabled]
Syslog Location                     | [Default]
IOT Blocking                        | [Disabled]
Country Lookup For Stats            | [Enabled]
CDN Whitelisting                    | [Enabled]
Display WebUI                       | [Enabled]

16/18 Tests Sucessful

[*] Local File Missing - [ chartjs-plugin-zoom.js ]

[*] Mounted File Missing - [ chartjs-plugin-zoom.js ]

=============================================================================================================

[#] 45701 IPs (+0) -- 1626 Ranges Banned (+0) || 1716 Inbound -- 20 Outbound Connections Blocked! [debug] [1]

**Comment by Adamm00** [comment]
`entered the IP and name
no ping from cmd`

This alone proves the blocking is working. You must be blocking the wrong address.
