### ISSUE TITLE
Allow connection on two machines (local network)

### ISSUE THREAD

**Issue by Micka35** [Adamm00/IPSet_ASUS#69]
Hello, 

First of all, thank you for this wonderful script that I have been using for several years!
I would like to use HwR (remote from HWinfo64) on a tablet, the information is then supposed to go through my local network.
Skynet blocks the communication between these two machines, when I disable it temporarily everything works.

HwR is based on a small software "HWInfo Transmlitter".
I tried to whitelist the sending IP but the result is the same.

I also have some little problems with another remote, the one of Audirvana (Audiophyle software) which sometimes has problems to connect.

How to authorize machines to communicate on my local network?
It seemed to me that the Firewall only blocked what came in or out from the WAN and not the LAN.

Thanks in advance :)

**Comment by Adamm00** [comment]
https://github.com/Adamm00/IPSet_ASUS/wiki#applicationexe-or-websitecom-is-blocked
