### ISSUE TITLE
Issues with VoWiFi

### ISSUE THREAD

**Issue by MaRCoMLXXV** [Adamm00/IPSet_ASUS#7]
Hi @Adamm00 , remember me? Left SNB a while ago in an emotional state, but I could really use your assistance, so I hope you don't mind me opening an issue on Github. If so, just let me know. 

Not sure whether this is Skynet-related but I'm sure you'll be able to tell. I'm trying to use Vodafone WiFi calling (VoWiFi) on our (supported) iPhones SE, which needs outgoing udp traffic to dpt 500 and 4500 to be allowed to connect to their (Dutch) voice server(s), of which I do not yet have the IP address. VoWiFi is enabled on both our phones but no matter what I do, none of the phones is able to connect to their server. 

I manually ran 

`iptables -A OUTPUT -p udp -m udp --dport 500 -j ACCEPT`
`iptables -A OUTPUT -p udp -m udp --dport 4500 -j ACCEPT`

but without success. Checked Skynet log entries, but couldn't find any blocked outgoing traffic. The ports mentions aboved don't show up in the stats either. Feel like I'm missing something here, but don't know what. Do our 68U's allow all outgoing traffic by default? Your assistance is greatly appreciated.

Best regards,
Marco

**Comment by Adamm00** [comment]
Not really familiar with VoWiFi as my local carriers are so behind. Only thing I can think of would be using -I to insert the rules to the top of the chain rather. Or put the rules in the forward chain?
