### ISSUE TITLE
Default filter.list

### ISSUE THREAD

**Issue by markster101** [Adamm00/IPSet_ASUS#76]
It is my understanding that filter.list is maintained as a url resource. I am wondering if you maybe open to suggestion to have
the option of storing the filter.list locally. This would give users additional flexibility to add additional url resources to the default list.

If the list is local Skynet would use it and periodically (once a day as is the default) download from the list. If the local list is not present Skynet would work as it is today.

**Comment by Adamm00** [comment]
Fixed in https://github.com/Adamm00/IPSet_ASUS/commit/ed4eef6811705a3a748b62714418ebb2280e5617
