### ISSUE TITLE
Import from a local file

### ISSUE THREAD

**Issue by sameer** [Adamm00/IPSet_ASUS#8]
###### Brief Description Of Issue
------------
Imported files must be imported from a URL. I would like to import files locally.

###### Steps To Reproduce Issue
------------
sh /jffs/scripts/firewall
Enter the number for importing a list. Try to put a filepath, no worky.

###### Expected Behaviour
------------
Skynet identifies filepaths vs URLs and handles them accordingly.

**Comment by Adamm00** [comment]
Sorry I didn't notice this earlier, I've added support for local file importing/deporting in [v5.6.9](https://github.com/Adamm00/IPSet_ASUS/commit/5ec3f808cc2f7b01223c416444e8755dcbaf9c48)

**Comment by punchHolecloud** [comment]
Aligned with the many points on 
or off a Wi-Fi network is skynet 
the best firewall source, in public places  !
