### ISSUE TITLE
Error when using local Banmalware list.

### ISSUE THREAD

**Issue by Tokarak** [Adamm00/IPSet_ASUS#82]
###### Brief Description Of Issue

changing banmalware filter list to a local file fails. This is an important function since it can be a hassle to host files on the web for personal use, and it is much easier to provide a local file.

###### Steps To Reproduce Issue
From GUI menu:
3 (Malware Blacklist) -> 2 (change filter list)
and input a local file url:
`file://[...]`

OR

`firewall banmalware file://[...]`

###### Expected Behaviour

Successful download and filter list change.

###### Output of ( sh /jffs/scripts/firewall debug info )

`[*] 404 Error Detected - Stopping Banmalware`

--------------------------------------

It seems to be stemming from this section in firewall.sh:

https://github.com/Adamm00/IPSet_ASUS/blob/e63393cd7a38db1964ff57ba7ff57979ba018652/firewall.sh#L3455-L3461

Firstly `curl -I` does not return headers for FILE protocol, but the file size and modification time only. Secondly the grep pattern only includes http(s). An update is required to support FILE protocol (and perhaps other protocols too, such as ftp; idk if anyone uses them).

It may also be useful to update similar code in other places; I am not aware of any because I am not very familiar with the source code.

**Comment by Tokarak** [comment]
Meanwhile, is there a temporary workaround to access local files through http, apart from hosting them on past.ee or such others? 

Are there any good ideas that can be easily implemented to fix this issue?

**Comment by Tokarak** [comment]
for reference:
`/usr/sbin/curl -fsL --retry 3 "$listurl" >/dev/null 2>&1 || { echo "[*] 404 Error Detected - Stopping Banmalware"; echo; exit 1; }`; removed on commit 6e9c7f7 in favour of the new HEAD only request. Date: 5 Nov 2018.
While this is obviously inefficient (especially for large files), this should allow FILE requests.

**Comment by Tokarak** [comment]
I don't see why the `curl -Isf "$listurl"|| [whatever]` wouldn't work...

**Comment by Tokarak** [comment]
Resolution of this issue will provide a work around (practically resolve) #76.

**Comment by Adamm00** [comment]
Thanks, merged
