### ISSUE TITLE
Enhancement - Crowdsec

### ISSUE THREAD

**Issue by RickBankers** [Adamm00/IPSet_ASUS#84]
It would be great of we could incorporate crowdsec into skynet. It would make the firewall even more awesome!

[https://github.com/crowdsecurity/crowdsec](https://github.com/crowdsecurity/crowdsecl)

[https://crowdsec.net/](https://crowdsec.net/)

**Comment by Tokarak** [comment]
Your link is broken:

https://github.com/crowdsecurity/crowdsec

**Comment by Adamm00** [comment]
I like where your heads at but their product is aimed at much different hardware so there's nothing really to incorporate. Im always open to suggestions though.
