### ISSUE TITLE
Disabling Logging of IOT Blocking devices

### ISSUE THREAD

**Issue by nickneos** [Adamm00/IPSet_ASUS#85]
I just started using this brilliant script and unless I'm missing something (very possible), doesn't look like you can disable the logging of IOT Blocking without disabling logging completely? 

If this feature doesn't exist could I request it as a possible feature enhancement? If I enable logging, it's just spammed by the IP Cameras I've added to the IOT blocking. I've disabled logging completely because of this, but now I can't use the WebUI stats.

**Comment by Tokarak** [comment]
Unfortunately, I don't think this feature exists in this script. 

You should also consider blocking the domain endpoints instead - it is cleaner, and It will stop being logged by Skynet. If you are using Diversion or Unbound, you should know how to do this. Then you can also sort the useful endpoints from the tracking endpoints, reducing your log size hopefully.

**Comment by Adamm00** [comment]
Finally got around to this, better late then never lol
