### ISSUE TITLE
Update Default IPSET List

### ISSUE THREAD

**Issue by steveg2088** [Adamm00/IPSet_ASUS#86]
Hi, after some digging, could you consider changing the default list as follows please:

Remove:

https://iplists.firehol.org/files/bi_any_2_30d.ipset 

Reason:  no longer exists on firehol

https://iplists.firehol.org/files/firehol_level3.netset 

Reason : too many false negatives

Finally, what the advice on using full bogons. Any risk with current skynet version?

**Comment by jumpsmm7** [comment]
I am able to use 
https://iplists.firehol.org/files/bi_any_2_30d.ipset 
just fine.
