### ISSUE TITLE
Skynet Won't Start - Internet Connection Broken (Multiple Routers)

### ISSUE THREAD

**Issue by TankedThomas** [Adamm00/IPSet_ASUS#87]
###### (Not So) Brief Description Of Issue

I've run into a rather major issue over the past two days with two different routers.
One is a DSL-AC68U running [gnuton's fork of Asuswrt-Merlin](https://github.com/gnuton/asuswrt-merlin.ng/), and one is an RT-AX86U running stock Asuswrt-Merlin custom firmware.

Both are running Diversion (standard w/pixelserv) and Skynet with a bunch of custom entries added to both (mainly just whitelisting sites which need to be unblocked). The same lists are on both, and I've been running this setup without issue for years on the DSL-AC68U. The other router (RT-AX86U) is a family member's, so it's in a different house on a completely different network even with a different ISP.

It started with the RT-AX86U completely losing internet connection. I found Skynet was stuck on "banmalware" but after rebooting it, killing the process, trying to reinstall skynet (uninstall then install, not just overwriting), and even resetting the router to default settings (via GUI and not clearing the extra settings with the checkbox), Skynet just hangs on startup.

If I kill Skynet and disable/remove it then reboot (reboot appears to be necessary), the internet connection comes back with Diversion untouched and otherwise working.
Skynet also complains about webui assets missing but even when manually downloading them, that only prevents it from complaining about fetching them, nothing else. All but one time (the latest try, after writing and editing this whole thing), the DSL-AC68U managed to download the webui assets. 

About a day ago, I updated the firmware on the DSL-AC68U. I reinstalled Diversion and Skynet after resetting to factory defaults post-update and it seemed to be working fine at the time. 

I did do another update on the DSL-AC68U without a reset last night (it seems I was late to the previous update). When checking for a difference between this and the other router afterwards, I noticed that Skynet had uninstalled itself. I don't think it's a lack of resetting as I've not done it much when updating in the past (less than I should have, frankly) and it's typically been fine.

There's really nothing out of the ordinary with my setup that I can think to mention. I have a script for updating my NextDNS linked IP (essentially just calling a URL) that I call via cron and a script I've placed under /jffs/scripts but the only issue I've had with that is it disappearing from the cron jobs. Seems unrelated but I do have that on both routers, so there's that. The issue with Skynet persists whether or not the NextDNS script is set up though. Maybe this is just how cron works on these routers; I'm not sure.

A few notes:
* Skynet playing up doesn't seem to completely kill the internet connection. Some things still work, but very few. Some external IP addresses work (e.g. 1.1.1.1) and some don't (e.g. 8.8.8.8 - I used DNS server addresses to test it because they're easy to remember). I've been watching a YouTube video whilst watching this despite Windows saying the internet is disconnected.
* After removing Skynet from the DSL-AC68U and rebooting, I've had no internet connection for about half an hour, with it literally only just reconnecting as I'm typing this sentence (rather ironic), despite the aforementioned YouTube video playing fine (but sites such as GitHub not loading pages). Discord died before I found Skynet had removed itself and I tried to reinstall it, and now after nuking Skynet again, Discord still won't work but everything else seems to (it works fine when using mobile data).
* Whenever (re)installing Skynet, it fails to download the webui assets automatically. 
Also, there's a brief kernel compatibility message displayed when installing via amtm but I'm not sure what it means.
("Warning: Kernel support protocol versions 6-6 while userspace supports protocol versions 6-7")
Happens on both routers. I'm wondering if this issue is related: [https://github.com/gonetx/ipset/pull/3](https://github.com/gonetx/ipset/pull/3)

Short of wiping EVERYTHING, which I'd rather avoid if possible (and might not even fix it), I'm not sure what to do.

I've attached the debug log minus my IP and devices, but I don't think it really reveals much. I know someone posted a very similar issue back in 2020 and fixed it by turning off Dual WAN but mine is off. The only thing I have set under there is my Primary WAN set to LAN 4 for my fibre ONT (the RT-AX86U is different as you set this up under the IPTV settings instead).

And after all of this... An hour and a half after I started putting this together and trying everything (including a LOT of waiting), the DSL-AC68U decided to let me reinstall Skynet without issue (I was just trying to reinstall it to get the same errors I kept getting in order to get a syslog). Fixed. No problems (for now). 
The same, unfortunately, cannot be said about the RT-AX86U, which continued to display the same issues after several hours (of testing, reinstalling, and a lot more waiting). I was going to open this issue solely for that router, until mine starting doing the same thing, albeit temporarily, it seems.

---
###### Steps To Reproduce Issue
Not sure since I've done nothing different (except for updating one of the routers - I updated the other too but after I had already found the issue present and tried for hours to fix it).

In the case of the DSL-AC68U, it seems to have started after updating the firmware, but since I wasn't monitoring the software via SSH before that, I can't be sure that's when it started. After reinstalling Skynet, _that_ is when I started having internet connection issues. The other router had no changes other than a new ethernet device (Steam Link) being plugged in and later removed.

Happens with both a manual install via curl and installing via amtm (though I believe they do the same thing anyway).

---
###### Expected Behaviour
Skynet starts successfully and doesn't kill my internet connection. 
Assets for webui can be downloaded without failing nor manual download.

---
###### Output of ( sh /jffs/scripts/firewall debug info )
[debug.txt](https://github.com/Adamm00/IPSet_ASUS/files/7979273/debug.txt)
The random gibberish at the start and end was part of the output when running "sh /jffs/scripts/firewall debug info > debug.txt". 
Not sure why it's there.

**Comment by Tokarak** [comment]
Please see [this](https://github.com/gnuton/asuswrt-merlin.ng/issues/123#issuecomment-955238396) comment on an issue in the fork. 
Try running:
`iptables -t raw -C PREROUTING -i "br0" -m set ! --match-set Skynet-Whitelist src -m set --match-set Skynet-Master src -j LOG --log-prefix "[BLOCKED - INBOUND] " --log-tcp-seq
uence --log-tcp-options --log-ip-options`
Also try running `iptables` with no arguments.
The output may help you with your problem.

**Comment by TankedThomas** [comment]
> Please see [this](https://github.com/gnuton/asuswrt-merlin.ng/issues/123#issuecomment-955238396) comment on an issue in the fork. Try running: `iptables -t raw -C PREROUTING -i "br0" -m set ! --match-set Skynet-Whitelist src -m set --match-set Skynet-Master src -j LOG --log-prefix "[BLOCKED - INBOUND] " --log-tcp-seq uence --log-tcp-options --log-ip-options` Also try running `iptables` with no arguments. The output may help you with your problem.

Thanks for the reply.
On the DSL-AC68U, I've tried running that command but it just returns `iptables: No chain/target/match by that name.` Running `iptables` by itself just gives `iptables v1.4.15: no command specified`.

Running `iptables -L` shows that I don't have a PREROUTING chain, so I'm not sure which one to use.
My chains are:
* INPUT
* FORWARD
* OUTPUT
* ACCESS_RESTRICTION
* DNSFILTER_DOT
* FUPNP
* INPUT_ICMP
* INPUT_PING
* NSFW
* OUTPUT_DNS
* OUTPUT_IP
* OVPN
* PControls
* PTCSRVLAN
* PTCSRVWAN
* SECURITY
* WGNPControls
* default_block
* logaccept
* logdrop
* logdrop_dns
* logdrop_ip
* other2wan

I haven't tried this on the RT-AX86U yet but gnuton mentions it's fixed as of October 2021 (the latest stable is 7 days prior to today), and the AX86U isn't running gnuton's fork anyway, hence why I posted it here instead of a particular Merlin repo.

Also, quick note, since Skynet resumed working on my DSL-AC68U at the end of my first post, it's had intermittent issues, often blocking certain connections, sometimes only from certain devices (e.g. Discord on my PC but not on my phone), so I've had to disable it in the interim.
