### ISSUE TITLE
provide description of secure mode

### ISSUE THREAD

**Issue by derekn** [Adamm00/IPSet_ASUS#88]
can you please describe what exactly the "secure mode" option does? I have not been able to find any documentation for this option, perhaps it could be added to the wiki.

I can see it disables ssh port wan access, but i've also noticed it seems to randomly block other port mappings but haven't been able to find anything in the logs regarding why. more info on how this feature works or what it does would be much appreciated

**Comment by Adamm00** [comment]
For the most part it prevents users from enabling (or being maliciously enabled) remote access via SSH and HTTPS as these settings can and will lead to your router being compromised. It also detects and neuters a few older strains of malware that targeted these routers from users who left these settings enabled. 

This should have no other effect on port mappings.

**Comment by derekn** [comment]
ok, makes sense. any idea why disabling it would fix a port being blocked that is forwarded (port 51820 for VPN)?

**Comment by Adamm00** [comment]
Not sure as everyone’s setup is different. But I can confidently say Skynet shouldn’t cause this behaviour. You can confirm this by either checking the logs (Skynet logs every packet it drops, no exceptions) or by simply temporarily disabling Skynet from the menu.
