### ISSUE TITLE
Wildcard whitelist support

### ISSUE THREAD

**Issue by decoderman** [Adamm00/IPSet_ASUS#89]
@Adamm00 do you see a way of supporting wildcard whitelist entries, say in the form of a regex like (\.|*.)diversion\.ch$ or simply *diversion\.ch$ ?

**Comment by Adamm00** [comment]
Currently domains are stripped with the following regex;

`sed 's~http[s]*://~~;s~/.*~~;s~www\.~~g;\~^$~d'`

So this would need to be modified accordingly and not have any other adverse effects when processing bulk domains.
