### ISSUE TITLE
Update from v7.2.8 to d41d8cd98f00b204e9800998ecf8427e

### ISSUE THREAD

**Issue by MarcoBuess** [Adamm00/IPSet_ASUS#92]
###### Brief Description Of Issue
[i] New Version Detected - Updating To  (d41d8cd98f00b204e9800998ecf8427e)
[i] Saving Changes
[i] Unloading Skynet Components
[*] Updating chart.js Failed
[*] Updating chartjs-plugin-zoom.js Failed
[*] Updating hammerjs.js Failed
[*] Updating skynet.asp Failed
[*] Updating firewall.sh Failed
[i] Restarting Firewall Service

###### Steps To Reproduce Issue
Run update through amtm Skynet interface.

###### Expected Behaviour
Update completes

###### Output of ( sh /jffs/scripts/firewall debug info )
Router Model; RT-AC87U
Skynet Version; v7.2.8 (19/10/2021) (44be5ae479cfdbbefa6398ada1cee8fc)
iptables v1.4.15
ipset v6.32, protocol version: 6
FW Version; 384.13_10 (Jun 28 2020) (2.6.36.4brcmarm)
Install Dir; /tmp/mnt/entware/skynet (11.2G / 14.1G Space Available)
SWAP File; /tmp/mnt/entware/myswap.swp (2.0G)
Uptime; 92 days, 34 hours, 0 minutes.
Ram Available; (179M / 249M)

--------------------                | ----------
| Test Description |                | | Result |
--------------------                | ----------

Internet-Connectivity               | [Passed]
Write Permission                    | [Passed]
Config File                         | [Passed]
Firewall-Start Entry                | [Passed]
Services-Stop Entry                 | [Passed]
Service-Event Entry                 | [Passed]
Profile.add Entry                   | [Passed]
SWAP File                           | [Passed]
Cron Jobs                           | [Passed]
NTP Sync                            | [Passed]
IPSet Comment Support               | [Passed]
Log Level 5 Settings                | [Passed]
Duplicate Rules In RAW              | [Passed]
IPSets                              | [Passed]
IPTables Rules                      | [Passed]
Local WebUI Files                   | [Passed]
Mounted WebUI Files                 | [Passed]
MenuTree.js Entry                   | [Passed]

-----------                         | ----------
| Setting |                         | | Status |
----------                          | ----------

Skynet Auto-Updates                 | [Enabled]
Malware List Auto-Updates           | [Enabled]
Logging                             | [Enabled]
Filter Traffic                      | [Selective]
Unban PrivateIP                     | [Enabled]
Log Invalid Packets                 | [Disabled]
Import AiProtect Data               | [Enabled]
Secure Mode                         | [Enabled]
Fast Switch List                    | [Disabled]
Syslog Location                     | [Default]
IOT Blocking                        | [Disabled]
Country Lookup For Stats            | [Enabled]
CDN Whitelisting                    | [Enabled]
Display WebUI                       | [Enabled]

18/18 Tests Sucessful

**Comment by Adamm00** [comment]
Looks like your ISP is blocking github

**Comment by MarcoBuess** [comment]
How is my ISP blocking github, when I'm able open/work this issue?

**Comment by MarcoBuess** [comment]
Can't confirm. Access to `raw.githubusercontent.com` working just fine. I made sure skynet isn't blocking access itself. Trying to whitelist `raw.githubusercontent.com` tells me URLs are already whitelisted. Anyway to get any more verbose debug logging?
