### ISSUE TITLE
No data to display in Skynet Statistics

### ISSUE THREAD

**Issue by qy2009** [Adamm00/IPSet_ASUS#93]
![image](https://user-images.githubusercontent.com/51539377/169385662-00355e83-5ed6-430c-9462-9aac1eefb008.png)
Hi,

Everytime I open Skynet Statictics , the log size is zero. and "no data to display". however it has banned so many IPs ?
I tried uninstalling Skynet and re-install for 3 times. still the same result.

I have clicked the button " Update Status" , same result.

and I am running Skynet for over one month now.

thanks

**Comment by Adamm00** [comment]
https://github.com/Adamm00/IPSet_ASUS/commit/6ebf3dafc067c3e1646a9cf2cad80d44068475ae
