### ISSUE TITLE
some IP's cannot be blocked for no obvious reason

### ISSUE THREAD

**Issue by sfortis** [Adamm00/IPSet_ASUS#96]
###### Brief Description Of Issue

Pls help because I'm loosing my mind :) 

It seems that some IP's cannot be blocked for no obvious reason!

For example, im trying to ban ip 157.175.96.3 (on amazon AS16509 asn), which is not in the whitelists!

skynet did nothing apparently!

```
=============================================================================================================





[i] Banning 157.175.96.3

[i] Saving Changes





=============================================================================================================





[#] 37764 IPs (+1) -- 2654 Ranges Banned (+0) || 813 Inbound -- 352 Outbound Connections Blocked! [ban] [1s]



router:/tmp/home/root# nmap -sn -PU 157.175.96.3

Starting Nmap 7.91 ( https://nmap.org ) at 2022-07-18 22:35 EEST

Nmap scan report for ec2-157-175-96-3.me-south-1.compute.amazonaws.com (157.175.96.3)

Host is up (0.12s latency).

Nmap done: 1 IP address (1 host up) scanned in 0.37 seconds

router:/tmp/home/root#
```

 

###### Steps To Reproduce Issue

firewall ban ip 157.175.96.3

nmap -sn -PU 157.175.96.3

###### Expected Behaviour

host cannot be reached

###### Output of ( sh /jffs/scripts/firewall debug info )

--------------------                | ----------
| Test Description |                | | Result |
--------------------                | ----------

Internet-Connectivity               | [Passed]
Write Permission                    | [Passed]
Config File                         | [Passed]
Firewall-Start Entry                | [Passed]
Services-Stop Entry                 | [Passed]
Service-Event Entry                 | [Passed]
Profile.add Entry                   | [Passed]
SWAP File                           | [Passed]
Cron Jobs                           | [Passed]
NTP Sync                            | [Passed]
IPSet Comment Support               | [Passed]
Log Level 6 Settings                | [Passed]
Duplicate Rules In RAW              | [Passed]
IPSets                              | [Passed]
IPTables Rules                      | [Passed]
Local WebUI Files                   | [Passed]
Mounted WebUI Files                 | [Failed]
MenuTree.js Entry                   | [Failed]

-----------                         | ----------
| Setting |                         | | Status |
----------                          | ----------

Skynet Auto-Updates                 | [Enabled]
Malware List Auto-Updates           | [Enabled]
Logging                             | [Disabled]
Filter Traffic                      | [Enabled]
Unban PrivateIP                     | [Enabled]
Log Invalid Packets                 | [Disabled]
Import AiProtect Data               | [Enabled]
Secure Mode                         | [Enabled]
Fast Switch List                    | [Disabled]
Syslog Location                     | [Default]
IOT Blocking                        | [Disabled]
Country Lookup For Stats            | [Enabled]
CDN Whitelisting                    | [Enabled]
Display WebUI                       | [Enabled]

16/18 Tests Sucessful

**Comment by dave14305** [comment]
https://ip-ranges.amazonaws.com/ip-ranges.json contains that subnet 157.175.0.0/16 as part of the CDN Whitelisting option.

**Comment by sfortis** [comment]
@dave14305 right...missed checking for class B subnets!
