### ISSUE TITLE
Custom DNS adresses lead to blocking when VPN ist turned on

### ISSUE THREAD

**Issue by Inrumpo** [Adamm00/IPSet_ASUS#97]
###### Environment
- Asus RT-AC86u Router
- Asus WRT Merlin 386.7
- amtm 3.3
- Skynet 7.2.8 (only script besides amtm)

WAN DNS settings:
![DNS Settings](https://user-images.githubusercontent.com/11300164/180569786-5ccbd42a-6d40-43b9-a7a5-ea424fe0fdf9.png)

###### Background
We had a power outage today. For whatever reason, my network stopped working after that. My router didn't manage to perform an NTP sync. This brought everything to a halt. Multiple reboots and a firmware update didn't help. I had to do a factory reset and now I'm in the process of restoring my network settings. Since the saved .tar settings file turned out to be invalid, I have to redo everything manually.

###### Brief Description Of Issue
When I turn on a VPN connection in the VPN settings, devices that are routed through this VPN (DNS configuration set to `exclusive`, using VPN director) will no longer be able to access the internet, _but_ only if I set a custom pair of DNS server IPs. This did work just fine until this afternoon. Unfortunately not anymore.

Possible scenarios in short:

1. DNS servers from ISP + VPN off → works ✅
2. DNS servers from ISP + VPN on → works ✅
3. DNS servers from provided list (e.g. Quad9) + VPN off → works ✅
4. DNS servers from provided list (e.g. Quad9) + VPN on → works ✅
5. Custom pair of DNS servers + VPN off → works ✅
6. Custom pair of DNS servers + VPN on → blocked ❌

Example of blocking when trying to access a website through my browser on my desktop PC:
`Jul 22 22:44:52 kernel: [BLOCKED - INBOUND] IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:cc:xx:xx:xx:xx:xx:xx:xx SRC=79.124.62.130 DST=MY-IP-REDACTED LEN=40 TOS=0`

###### Steps To Reproduce Issue
1. set a custom pair of DNS servers (not from the provided list
2. in this case `103.86.96.100` and `103.86.99.100`
3. activate a VPN connection

###### Expected Behaviour
Using a VPN with a custom pair of DNS servers provided by the VPN service should work just fine, as it did before.

###### What I've tried to solve this without success
- router reboot
- refresh VPN whitelist
- refresh whitelist entries
- manually whitelist the DNS servers in question, but doesn't work (`ipset v7.6: Element cannot be added to the set: it's already added`)
- testing different WAN DNS settings (enable/disable `DNSSEC support`/`DNS Privacy Protocol` etc.)

###### Output of ( sh /jffs/scripts/firewall debug info ) with VPN off
> Router Model; RT-AC86U
> Skynet Version; v7.2.8 (19/10/2021) (cd9e05f9b3897f144dd71260906a761a)
> iptables v1.4.15 - (eth0 @ 192.168.1.1)
> ipset v7.6, protocol version: 7
> IP Address; (MY IP)
> FW Version; 386.7_0 (Jun 22 2022) (4.1.27)
> Install Dir; /tmp/mnt/SamsungUSB/skynet (25.7G / 29.3G Space Available)
> SWAP File; /tmp/mnt/SamsungUSB/myswap.swp (2.0G)
> Banned Countries; af cn ir iq kz kp ng ps ru ae
> Uptime; 0 days, 5 hours, 31 minutes.
> Ram Available; (83M / 430M)
> 
> ---------------                          | ------------     | ---------------      | ----------
> | Device Name |                          | | Local IP |     | | MAC Address |      | | Status |
> ---------------                          | ------------     | ---------------      | ----------
> 
> Device 1                               | 91.138.4.1       | x    | Online
> Device 2                            | 192.168.1.15     | x    | Inactive
> Device 3                             | 192.168.1.32     | x    | Online
> Device 4                              | 192.168.1.33     | x    | Online
> Device 5                              | 192.168.1.61     | x    | Inactive
> Device 6                               | 192.168.1.66     | Unknown              | Offline
> Device 7                                     | 192.168.1.68     | Unknown              | Offline
> Device 8                             | 192.168.1.102    | Unknown              | Offline
> Device 9                              | 192.168.1.155    | x    | Inactive
> Device 10                                   | 192.168.1.156    | Unknown              | Offline
> Device 11                         | 192.168.1.177    | x    | Online
> Device 12                             | 192.168.1.236    | x    | Inactive
> 
> 
> --------------------                | ----------
> | Test Description |                | | Result |
> --------------------                | ----------
> 
> Internet-Connectivity               | [Passed]
> Write Permission                    | [Passed]
> Config File                         | [Passed]
> Firewall-Start Entry                | [Passed]
> Services-Stop Entry                 | [Passed]
> Service-Event Entry                 | [Passed]
> Profile.add Entry                   | [Passed]
> SWAP File                           | [Passed]
> Cron Jobs                           | [Passed]
> NTP Sync                            | [Passed]
> IPSet Comment Support               | [Passed]
> Log Level 5 Settings                | [Passed]
> Duplicate Rules In RAW              | [Passed]
> IPSets                              | [Passed]
> IPTables Rules                      | [Passed]
> Local WebUI Files                   | [Passed]
> Mounted WebUI Files                 | [Passed]
> MenuTree.js Entry                   | [Passed]
> 
> 
> -----------                         | ----------
> | Setting |                         | | Status |
> ----------                          | ----------
> 
> Skynet Auto-Updates                 | [Enabled]
> Malware List Auto-Updates           | [Enabled]
> Logging                             | [Enabled]
> Filter Traffic                      | [Enabled]
> Unban PrivateIP                     | [Enabled]
> Log Invalid Packets                 | [Disabled]
> Import AiProtect Data               | [Enabled]
> Secure Mode                         | [Enabled]
> Fast Switch List                    | [Disabled]
> Syslog Location                     | [Default]
> IOT Blocking                        | [Disabled]
> Country Lookup For Stats            | [Enabled]
> CDN Whitelisting                    | [Enabled]
> Display WebUI                       | [Enabled]
> 
> 18/18 Tests Sucessful
> 
> ======================================================
>  
> [#] 35572 IPs (+0) -- 36355 Ranges Banned (+0) || 113 Inbound -- 0 Outbound Connections Blocked! [debug] [5s]

I'm running out of options. How can I stop this blocking?

**Comment by Inrumpo** [comment]
Through some more testing I got "Custom pair of DNS servers + VPN"  to work, _but only_ if `Accept DNS Configuration` is set to anything other than `Exclusive` in the VPN settings.

This doesn't solve the problem since having it not set to `Exclusive` does cause DNS leaks.

**Comment by Inrumpo** [comment]
I found the solution: For whatever reason I the WAN DNS servers have to be set to anything other than the VPN provider's DNS servers.

**Comment by neatchee** [comment]
I ran into this issue completely independent of VPN, when using an internal pihole as the DNS provider.

During startup of skynet, the process hangs - probably trying to do a DNS lookup while the firewall rules aren't set up, and blocking the pihole from reaching the internet to resolve requests.

As mentioned above, the solution is to set the WAN DNS to anything other than an in-NAT DNS server
