### ISSUE TITLE
Cant block a server immediately

### ISSUE THREAD

**Issue by GPRJ21** [Adamm00/IPSet_ASUS#98]
###### Brief Description Of Issue
AMTM - Hit IP Ban and no blocking

###### Steps To Reproduce Issue
Hi there. I have a regular ISP provider, static ip and an Asus RT86 up to date.

 Sometimes i am in heavy lag server and the best scenario iis ban and search again for a new one (gaming).

I find the game serve ip - port 3659 - in the system log panel. Easy

I grab the IP but nothing happns when i ban it.
I made a block test  using ROUTES in the LAN panel, and worked fine. Blocked as soon as i hit apply.

Once in a while using Skynet  blocks, but takes more than 5 minutes to do it. But 99% of the time i cant banthe server.

Skynet dont block it imeadiatly, but block AFTER the game ends. I mean. When i start a game and notice it is very very lag, i cant block it, but if i get redirected to the same server i previously block, skynet works.

Resume: cant block right away but it prevents to join the server i blocked in futures matches.

###### Expected Behaviour
Block the game server immediately

###### Output of ( sh /jffs/scripts/firewall debug info )

Tks all

**Comment by Adamm00** [comment]
Skynet won't drops any current connections, only future connection attempts.
