### ISSUE TITLE
Does Skynet require the custom Asus Merlin firmware?

### ISSUE THREAD

**Issue by whisperdancer** [Adamm00/IPSet_ASUS#99]
Will it also work with stock Asus firmware? 

"...Skynet is the first comprehensive IP banning and security tool exclusively for Asus Devices...." Makes no mention of a Merlin firmware requirement. When I read this I assumed it works on Asus routers. Just purchased a new Asus router and can't install Skynet, my favorite firewall on stock.

**Comment by Adamm00** [comment]
Unfortunately Merlin only.
